### ISSUE TITLE
Play Next is broken on Spicetify 2.9.2/Spotify 1.1.81.604.gccacfc8c

### ISSUE THREAD

**Issue by WildGenius** [daksh2k/Spicetify-stuff#10]

**Comment by daksh2k** [comment]
Hey do you know how to access console in Spotify? If so can you share any error info regarding this?

If not, does this happen with albums only or tracks and playlist too?

**Comment by daksh2k** [comment]
Should be fixed now.
Spotify removed the internal `hermes` api's in 1.1.81 which was used to fetch album details.

Now the extension fetches from Web API by default.

> Devtools don't seem to work (I ran spicetify enable-devtool and tried to hit ctrl+shift+i, but nothing's happening)

I haven't update spotify for a while, I'm still on like `1.1.74` but they removed devtools in 1.1.80 I think but there is a [workaround](https://discord.com/channels/842219447716151306/842819014941212682/953149451000762388) if you are interested.

**Comment by WildGenius** [comment]
Can confirm albums are working now. Thanks for the quick fix and for the devtools workaround as well!
