### ISSUE TITLE
[Bug]: Error displayed volume pourcentage

### ISSUE THREAD

**Issue by TheGeeKing** [daksh2k/Spicetify-stuff#100]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bits) 1.2.16.947.gcfbaa410
- Spicetify version: Spicetify v2.21.0
```

### 📝 Description

When listening on phone spotify shows the volume bar as greyed out cf image1
If you use fullscreen mode it will display "%%" as the volume cf image2

Should display the volume. I guess you can't retrieve it, so if you can't retrieve the volume maybe show a "?", no volume bar, a message, or anything else.

### 📸 Screenshots

![image1](https://github.com/daksh2k/Spicetify-stuff/assets/58857539/e9e8a23d-bfe5-4e5b-b6f8-546db6eff5d2)
![image2](https://github.com/daksh2k/Spicetify-stuff/assets/58857539/cd66aeb7-d2b0-479a-a67c-538a003f2e52)

**Comment by daksh2k** [comment]
This is not a bug, it's just how it was intended, and the volume bar is already greyed out.
But still changed the functionality to hide the percentage altogether when disabled in `v2.3.1`.

**Comment by TheGeeKing** [comment]
The "%%" is intended?
