### ISSUE TITLE
[Bug]: Full Screen Mode Text Contrast Adaptation

### ISSUE THREAD

**Issue by karimawii** [daksh2k/Spicetify-stuff#103]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify 1.2.17.834.g26ee1129
- Spicetify v2.22.1
```

### 📝 Description

Text color contrast with dynamic solid color background, it's just white, doesn't turn black for brighter backgrounds.

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/69881381/a33c76a2-c40f-4741-bca3-854faeda51fa)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/69881381/fc2da5e9-719f-4254-a3fc-d97e79241401)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/69881381/7a5e3649-a81b-433a-b6f6-f4d19489e406)

**Comment by daksh2k** [comment]
It's working fine for me. You need to change the behaviour in settings.

![image](https://github.com/daksh2k/Spicetify-stuff/assets/42179185/fe66ad1f-3fa0-462c-99aa-96b99c34c667)


![image](https://github.com/daksh2k/Spicetify-stuff/assets/42179185/cb76f382-f54b-486b-96d7-681a6cd0954c)

**Comment by karimawii** [comment]
Oh, I didn't know it was that option, I apologize.

**Comment by daksh2k** [comment]
No worries, Hope you like the extension !
Also you try out, there is a new background option called `Animated album art`. It's a little resource intensive, but looks good !

**Comment by karimawii** [comment]
Yeah I tried it out, it looks super cool but yeah it uses a bunch of resources.

I'm thinking of using the TV mode on a raspberry pi with the linux version of Spotify and write a python script to match some LED colors with the album art vibrant color, I think it will look cool, just wanted to share that in case you wanna give any insights.

**Comment by daksh2k** [comment]
Oh, interesting, you can look at the `webNowPlaying` extension on the official spicetify repo to expose stuff via websockets. For color fetching you can take a look at any reference.
Would love to see the results. Good luck !
