### ISSUE TITLE
[Feature Request]: add support for vertical monitor

### ISSUE THREAD

**Issue by ItsTatsuya** [daksh2k/Spicetify-stuff#105]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

An option to alternate the placement of lyrics, positioned either laterally adjacent to the media player or situated below it, catering to users having vertical monitor configuration

might be a niche feature request since most of the people dont have vertical monitors

**Before**
![image](https://github.com/daksh2k/Spicetify-stuff/assets/87627258/59bae342-43ec-414e-8cc1-d4858aeb1a8b)

**After**
![Screenshot (54)](https://github.com/daksh2k/Spicetify-stuff/assets/87627258/e5fd4faa-b29e-425f-8b55-8fed29259752)

**Comment by daksh2k** [comment]
Hi, I added basic support to the default mode, you can try it out and share any feedback you have.
The vertical mode has to be enabled in settings first (it's enabled by default), and when the height is bigger than the width the UI will automatically change.

**Comment by ItsTatsuya** [comment]
The implementation looks good, thank you for adding support
