### ISSUE TITLE
[Bug]: Lyrics in full screen mode extension

### ISSUE THREAD

**Issue by wuhurmuhu** [daksh2k/Spicetify-stuff#106]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.17.834.g26ee1129
- Spicetify version: 2.22.2
```

### 📝 Description

Lyrics do not show up in full screen mode automatically. I have to click on the lyrics button on the sidebar, go to synced or unsynced (unsynced if synced not available) then go to fullscreen mod and turn off then on the Lyrics button in it's configuration.
If I leave fullscreen mode the process above has to be repeated.
Note: This started about a week ago, tried uninstalling and reinstalling the lyrics plus extension but same issue.
Issue also reappears when skipping songs
Posted issue at lyrics plus and got closed because it was 'general help' and was told to turn on lyrics in fullscreen mode...which is obviously on
![image](https://github.com/daksh2k/Spicetify-stuff/assets/141845310/163f1810-8665-4fdb-a797-48dac789f181)

### 📸 Screenshots

Lyrics at sidebar
![image](https://github.com/daksh2k/Spicetify-stuff/assets/141845310/8431a6a5-62b3-4d82-8f2f-e9008f97fd86)
Fullscreen mode (auto hide if no lyrics)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/141845310/e2137e3b-205e-4ded-9eac-4e9a22ad9faa)
After turning lyrics button off and on in configuration
![image](https://github.com/daksh2k/Spicetify-stuff/assets/141845310/8c39fe3b-5dc3-47f2-b8a9-05abed924243)

**Comment by wuhurmuhu** [comment]
By "turning off and on the lyrics button" it was already on, I just press off then on again.

**Comment by daksh2k** [comment]
Can you turn off the auto hide setting and check again? That setting might be a little buggy.

**Comment by wuhurmuhu** [comment]
Checked, still facing the same issue

**Comment by daksh2k** [comment]
Can you add a video of the process, so I can understand it more clearly, the only setting that may be interfering with the process is the `auto hide lyrics` one

**Comment by wuhurmuhu** [comment]
https://github.com/daksh2k/Spicetify-stuff/assets/141845310/80856f26-a32d-457b-86d2-beed692cc932

**Comment by daksh2k** [comment]
Just right-click on the synced lyrics tab inside `lyrics-plus`, that will set it as default. It's because you have selected karaoke as default this issue is happening. Also, turn off the auto-hide setting by default if it's not working. It will work fine the other way.

**Comment by wuhurmuhu** [comment]
Thanks!
