### ISSUE TITLE
[Bug]: volumePercentage.js bug with last Spotify version

### ISSUE THREAD

**Issue by xerta555** [daksh2k/Spicetify-stuff#108]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Volume Percentage

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.18.999.g9b38fc27
- Spicetify version: v2.22.2
```

### 📝 Description

Hi

Your volumePercentage.js extension no longer work on the last Spotify version (`1.2.18.999.g9b38fc27`), either through manual install nor Marketplace install.

Works fine with the `1.2.18.999.g9b38fc27-20` version.

No logs related to the extension found in the DevTools console.

Could you take a look please ? :)

Thank you in advance.

**Comment by daksh2k** [comment]
Can you try removing everything(theme and extensions) and test then, I have the same versions, and it's working fine for me. 
It might be some theme is messing with it.
P.S. Just export your settings in marketplace settings and reset, and after testing you can import again

**Comment by xerta555** [comment]
> Can you try removing everything(theme and extensions) and test then, I have the same versions, and it's working fine for me. It might be some theme is messing with it. P.S. Just export your settings in marketplace settings and reset, and after testing you can import again

Hm ok go for test

**Comment by daksh2k** [comment]
Can you try running `document.querySelector(".volume-bar");` in devtools and share ss of what you get, as attached below, see the volume bar is highlighted when I hover over the element in devtools.


![image](https://github.com/daksh2k/Spicetify-stuff/assets/42179185/4f7ad7b2-28c1-4f25-898f-d27f1de9c60e)

**Comment by xerta555** [comment]
Ok but where/how in the console i have to run your command ?

**Comment by daksh2k** [comment]
First, enable devtools by running `spicetify enable-devtools`, then open it by `ctrl+shift+i` or `cmd+option+i` inside Spotify to open.

And click on the console tab.

**Comment by xerta555** [comment]
> First, enable devtools by running `spicetify enable-devtools`, then open it by `ctrl+shift+i` or `cmd+option+i` inside Spotify to open.
> 
> And click on the console tab.

I know about this part, i just don't know how to run your command
![image](https://github.com/daksh2k/Spicetify-stuff/assets/20888017/bfcb9caf-9150-40de-a618-a1ec9bde4d46)

**Comment by daksh2k** [comment]
Oh lol, just paste it right beside the blue arrow not in the filter box(clear it), see my attached ss in the previous comment.

**Comment by xerta555** [comment]
> Oh lol, just paste it right beside the blue arrow not in the filter box(clear it), see my attached ss in the previous comment.

Like that ?

![image](https://github.com/daksh2k/Spicetify-stuff/assets/20888017/feac4c3b-54ba-4730-9c50-7d8950eaf74d)

**Comment by daksh2k** [comment]
Yeah, like that, not sure why it's coming as null. Weird

Can you try clicking on the button to the left of elements tab and select the volume bar inside spotify, and share ss of devtools what's opening up.

I have the exact same versions, it's working fine for me. You may need to do a clean install, if this doesn't work.

**Comment by xerta555** [comment]
> Can you try clicking on the button to the left of elements tab and select the volume bar inside spotify, and share ss of devtools what's opening up.

Same result happened.

> I have the exact same versions, it's working fine for me. You may need to do a clean install, if this doesn't work.

OK, I admit i'm a bit scared to reinstall Spotify just for that, so i'll go back to the previous version and check if this bug disappears in future versions

Thx anyway for your help/support and have a good day.

**Comment by xerta555** [comment]
Hi @daksh2k i just did a clean install of Spotify (1.2.20.1210.g2a8a8a57) and Spicetify (v2.23.2)

Same issue, the extension won't works and same result on Console tab of DevTools.

Some extensions works fine (goToSong, fullAppDisplay and power-bar), some won't (your one, copytoclipboard2 and fullAlbumDate), maybe it would help us to see things more clearly..

Another change with the Spicetify/Spotify cleanup setup: is now show the note (second line after the command)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/20888017/26c0d360-f663-4631-9c9b-57c7273fa6ed)


The bug is either in the Experimental settings (simple method to compare my ones with yours ?) nor in Spicetify (a fairly recent bug had broken all the extensions for quite a few users, perhaps this is a repeat ?)

Back to 1.2.18.999.g9b38fc27-20, your extension work again.

**Comment by daksh2k** [comment]
There was some change done in #109  , that should have fixed it. I still have the `1.2.19` version, it works fine.
Haven't got `1.2.20` version yet, so can't say.
