### ISSUE TITLE
[Save Playlists] Add playlist cover to saved playlist (enhancement)

### ISSUE THREAD

**Issue by jabreen** [daksh2k/Spicetify-stuff#11]
Is this at all possible? Thanks!

**Comment by daksh2k** [comment]
Yeah seems possible, I'll look into it.

**Comment by jabreen** [comment]
Sounds good, thanks!

**Comment by daksh2k** [comment]
Added in https://github.com/daksh2k/Spicetify-stuff/commit/fbe3a549d5ceb3b6062e6a591fce6f75a5611fa5.
Check it out! Now the playlist cover should be same as the original playlist in most of the cases.

**Comment by jabreen** [comment]
Thank you very much!
