### ISSUE TITLE
[Bug]: Black screen on Full Screen Mode

### ISSUE THREAD

**Issue by AstudilloMarillo** [daksh2k/Spicetify-stuff#110]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.19.941.gbf202593
Spicetify v2.21.0
Theme: marketplace
Extensions: fullAlbumDate.js, spotifyBackup.js, savePlaylistsWrapper.js, autoSkipWrapper.js, playNextWrapper.js, power-bar.js, playlist-icons.js, copytoclipboard2.js, css-editor.js, volumePercentage.js, QueueTime.js, SleepTimer.js, part_selector.js, spotdj.js, goToSong.js, skip-song-part.js, startup-page.js, fullAppDisplayMod.js, fullScreenWrapper.js, sortByPlayCount.js, seekSong.js, autoSkipPattern.js, toggleLyricsPlusFullscreen.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

Since last time I had to re-Spicetify Spotify, a few days ago, the Full Screen plugin doesn't work any more. It just shows a black screen instead of the title, album art, background.

### 📸 Screenshots

![2023-09-01_13-18-36](https://github.com/daksh2k/Spicetify-stuff/assets/136191659/ba3f2b43-54fe-4ac5-a7a8-a42a18954fc2)

**Comment by daksh2k** [comment]
Update your spicetify, by running `spicetify upgrade` and then `spicetify restore backup apply`

**Comment by AstudilloMarillo** [comment]
> Update your spicetify, by running `spicetify upgrade` and then `spicetify restore backup apply`

Mmh, I did that, but now that I do it a second time it now works correctly. Maybe I didn't do it properly the first time, my bad.
