### ISSUE TITLE
[Feature Request]: Add support for xdg-screensaver

### ISSUE THREAD

**Issue by GamzeeRakoon** [daksh2k/Spicetify-stuff#113]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

When using the full screen mode extension on Linux it won't disable the screensaver, and it will eventually go in to sleep mode, I work around this by playing a YouTube video in the background, but this isn't an ideal solution.

### ➕ Additional Information

By adding support for the free desktop xdg-screensaver specification, which is a standard across the Linux desktop. And with this you can disable the screensaver when in full screen mode across all Linux distributions.

https://freedesktop.org/wiki/Software/xdg-utils/
https://portland.freedesktop.org/doc/xdg-screensaver.html

**Comment by daksh2k** [comment]
Hi, I don't have control over the desktop environment inside the extension, as it's just a javascript running inside Spotify itself. The control is with Spotify itself, doesn't matter what extension you are using. 
So I'm afraid I can't help you with this.
