### ISSUE TITLE
[Bug]: Hide Stock Button" not working

### ISSUE THREAD

**Issue by danielc0603** [daksh2k/Spicetify-stuff#114]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.19.941.gbf202593
Spicetify v2.23.1
Theme: Hazy / Base
Extensions: spotifyBackup.js, beautiful-lyrics.js, group-session.js, playing-source.js, fullAlbumDate.js, fullScreenWrapper.js, QueueTime.js, seekonscroll.js, queuePanel.js, scannables.js, theme.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

- Open Spotify
- Open Full Screen Configuration
- Toggle On "Hide Stock Button"
- Error: The stock button is not hidden.

### 📸 Screenshots

![CleanShot 2023-09-09 at 18 30 18](https://github.com/daksh2k/Spicetify-stuff/assets/74224007/ee29fdef-8841-474f-9f45-9fba6491563c)

**Comment by daksh2k** [comment]
That full screen button in the right corner is not the stock button, I think it's added by another extension, probably `beautiful-lyrics`. So I'm afraid I won't be able to help you with this.
