### ISSUE TITLE
[Bug]: Play next not working on local songs

### ISSUE THREAD

**Issue by adambnmohd** [daksh2k/Spicetify-stuff#118]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [x] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Play Next

### ℹ Environment / Computer Info

```Markdown
Spicetify v2.23.2
```

### 📝 Description

Extensions/playNext.js doesnt work on locally added songs

**Comment by daksh2k** [comment]
Added in https://github.com/daksh2k/Spicetify-stuff/commit/f3346f766843f3d3de390539f450913e12c27f28
