### ISSUE TITLE
[Feature Request] Queue in fullscreen mode

### ISSUE THREAD

**Issue by MisterPharaoh** [daksh2k/Spicetify-stuff#12]
Dear daksh2k,

I hope that one day the ability to see the queue in full-screen mode becomes available. I would say this can be in the same place as the lyrics are, which is on the right of the screen. Hopefully this is doable, as it would make the full-screen extension perfect. Thanks and have a great day!

Kind regards,

Mark

**Comment by daksh2k** [comment]
I'll see what can be done!

**Comment by MisterPharaoh** [comment]
Thank you, hope it works out!

**Comment by thegoldknight** [comment]
A quick suggestion for this enhancement. 

Maybe activate the queue list by pressing the context icon on the top left corner? And then making it slide over/expand from the left, similar to a Notion or Safari sidebar. Although having it on the right wouldn't be a bad idea either. 
<img width="1180" alt="Screenshot 2023-06-06 at 4 07 59 PM (2)" src="https://github.com/daksh2k/Spicetify-stuff/assets/135397968/139d1094-ab8d-4437-9436-f51f94ba8381">

**Comment by daksh2k** [comment]
This was added, earlier for everone, but now can be enabled from settings in `v2.7.0` @MisterPharaoh @thegoldknight 
Only took 2 years lol.

**Comment by MisterPharaoh** [comment]
@daksh2k I'm seeing this late, but thanks a lot for the addition! It works nicely and looks good. Take care and good luck with the project :)
