### ISSUE TITLE
[Bug]: Background Changes on fullscreen

### ISSUE THREAD

**Issue by JxxIT** [daksh2k/Spicetify-stuff#125]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.26.1187.g36b715a1
Spicetify v2.28.1
Theme: Default Dynamic / Base
Extensions: section-marker.js, beautiful-lyrics.js, fullScreenWrapper.js, adblock.js, default-dynamic.js, Vibrant.min.js
Custom apps: marketplace, eternal-jukebox, lyrics-plus
```

### 📝 Description

If you go into fullscreen mode, and go to a other desktop, the fullscreen-mode shows as the desktop background. You cannot interact with it.

### 📸 Screenshots

<img width="1403" alt="Scherm­afbeelding 2023-12-10 om 15 54 46" src="https://github.com/daksh2k/Spicetify-stuff/assets/110342008/a2b70ee5-2e31-411e-bace-9ea8c06e603d">

**Comment by daksh2k** [comment]
https://github.com/daksh2k/Spicetify-stuff/assets/42179185/0f36c8c5-bb53-4c6f-8219-72b057128902

For me it's very smooth, didn't get this issue, does it happen every time? It would be better if you could add a video.

**Comment by JxxIT** [comment]
I don't know what I did, but I am not able to reproduce it anymore.
