### ISSUE TITLE
[Bug]: Automatically closing fullscreen

### ISSUE THREAD

**Issue by JxxIT** [daksh2k/Spicetify-stuff#126]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.26.1187.g36b715a1
Spicetify v2.28.1
Theme: Default Dynamic / Base
Extensions: section-marker.js, beautiful-lyrics.js, fullScreenWrapper.js, adblock.js, default-dynamic.js, Vibrant.min.js
Custom apps: marketplace, eternal-jukebox, lyrics-plus
```

### 📝 Description

Steps to reproduce:

1. Make sure that spotify is in fullscreen
2. Open tv or default mode.
3. Press esc or exit full screen.
4. See that spotify is no longer in fullscreen.

**Comment by daksh2k** [comment]
The purpose of the extension is not to make the default spotify window fullscreen, it's to provide a different experience when using this extension. "full screen" is the name of the extension, The esc key is used to exit this extension/ full screen

**Comment by JxxIT** [comment]
Yeah I understand, but when you hit the esc key or close the extension, spotify automatically closes fullscreen.

**Comment by daksh2k** [comment]
Oh if you are using mac and by default use spotify in full screen state, you can just turn this setting off, it won't change your behaviour when entering and exiting this extension.

<img width="607" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/f9210300-0674-43f6-a45e-1b81774d44a4">

**Comment by JxxIT** [comment]
Oh yeah, that fixes it.
