### ISSUE TITLE
[Bug]: Button/Icon and Hotkeys assigned to Full Screen Extension is not working

### ISSUE THREAD

**Issue by OverRevvv** [daksh2k/Spicetify-stuff#129]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Save Playlists

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows Version : 1.2.19.941.gbf202593
Spicetify version : 2.23.0
Extensions: CopyToClipboard.js, fullscreen.js, JapaneseRomanjiLyrics.js.
```

## After the latest update of `Full Screen` Extension 
1. Button or Icon to activate `Full Screen` is not showing in Home Page even tho it's installed as you can see in the screenshot.

2. The hotkeys assigned to trigger `fullScreen` is also not working (`F`) as well.

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/98686837/4e5d0193-0a11-41e9-b6fb-828b96db441a)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/98686837/d32961c1-57c7-4d40-b31f-5fed69e87bd3)

**Comment by daksh2k** [comment]
Please update your Spotify and Spicetify versions, should work fine then.

**Comment by OverRevvv** [comment]
@daksh2k 

### Updated both but it's still not working
Spotify : 
![image](https://github.com/daksh2k/Spicetify-stuff/assets/98686837/6a37e57e-aff4-4fa0-ab19-0fd8b31e9abf)

Spicetify : 
![image](https://github.com/daksh2k/Spicetify-stuff/assets/98686837/318608f3-6dc3-4d95-ab46-861081eefe21)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/98686837/5e5a0286-9893-4c2e-98bc-84c951144d49)


### After Update : 
![image](https://github.com/daksh2k/Spicetify-stuff/assets/98686837/fe009a6b-b04c-4314-a6c9-1730860c8991)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/98686837/48d01e0a-d2fd-433c-a793-9969beb3ad07)

**Comment by LightD31** [comment]
I have the same problem, I can't use full screen, neither by hotkey nor icon
```
Spotify  pour Windows (64 bits)
1.2.26.1187.g36b715a1
Spicetify v2.28.1
```

**Comment by michaelclark09** [comment]
+1 to this issue, tried delete/reinstall of the extension too

![Screenshot 2023-12-12 115207](https://github.com/daksh2k/Spicetify-stuff/assets/17025334/ec9b5eae-77d9-43a8-bfd5-2af21d94789d)
![Screenshot 2023-12-12 115340](https://github.com/daksh2k/Spicetify-stuff/assets/17025334/5d5b7bd1-3f8a-4420-9462-b317de1867bd)
![Screenshot 2023-12-12 115612](https://github.com/daksh2k/Spicetify-stuff/assets/17025334/a6e58322-2d1c-4c3f-b0e1-fe93b2873acf)
![Screenshot 2023-12-12 115629](https://github.com/daksh2k/Spicetify-stuff/assets/17025334/bc7c30a0-b938-433b-ad3a-74029a59bca1)

**Comment by jaeger-2601** [comment]
+1

**Comment by kutawhat** [comment]
Samу with me

**Comment by ishant010301** [comment]
yup, the bug still persists. I had this working before but after reinstalling spicetify after a windows reset it stopped showing up.

**Comment by daksh2k** [comment]
Had some issues with my custom domain, switched registrars today, configured it, and should be able to access it now. Just restart/reload Spotify.
@OverRevvv @ishant010301 @kutawhat @jaeger-2601 @michaelclark09

**Comment by michaelclark09** [comment]
Confirmed resolved after relaunching spotify

**Comment by OverRevvv** [comment]
@daksh2k Confirmed as well

**Comment by ishant010301** [comment]
It now working, my laptop restarted and it started working...

**Comment by mccalltristan** [comment]
Ive just encountered this, or at least something similar. Is anyone still having this issue?

**Comment by OverRevvv** [comment]
@mccalltristan 
> Ive just encountered this, or at least something similar. Is anyone still having this issue?

This issue has been fixed, you probably should try updated versions of Spotify and Spicetify, Update both of them and check again.
