### ISSUE TITLE
Genius Lyric Annotations don't show in Fullscreen

### ISSUE THREAD

**Issue by dinesh-58** [daksh2k/Spicetify-stuff#13]
As per title, selecting Genius is LyricsPlus, then clicking on lyrics inside fullscreen shows just a white block. 

Inside LyricsPlus:
![image](https://user-images.githubusercontent.com/86787475/161969582-96a0632f-5f68-4e73-95cc-5102297252db.png)

Inside fullscreen: 
![image](https://user-images.githubusercontent.com/86787475/161969743-9ba281ec-b134-46c5-9725-9f2ac54a0a76.png)

Just wanna say this is a great extension ♥

**Comment by daksh2k** [comment]
Should be fixed now, it was actually caused by `lyrics-plus` not exposing certain colors in `full-screen` mode.
So added the colors from the extension itself.

And glad you like the extension :) !

**Comment by dinesh-58** [comment]
thanks for the quick fix
