### ISSUE TITLE
[Bug]: Animated Album Art Background Blur not working

### ISSUE THREAD

**Issue by voidlesity** [daksh2k/Spicetify-stuff#130]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.4.912.g949d5fd0
Spicetify v2.28.1
Theme: Comfy / catppuccin-frappe
Extensions: spotifyGenres.js, power-bar.js, autoplay.js, seekonscroll.js, hidePodcasts.js, fullScreenWrapper.js, CoverAmbience.js, featureshuffle.js, songstats.js, group-session.js, beautiful-lyrics.js, volumePercentageWrapper.js, theme.js
Custom apps: marketplace, eternal-jukebox, stats, lyrics-plus, new-releases
```

### 📝 Description

Changing the Background Blur in the options under Background Modification doesn't change the blur intensity on the background its a very minor thing I just happened to notice

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/104164715/e9ba84c9-27df-4dba-a4cd-1416653e5597)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/104164715/8485d026-3379-4d97-bda8-1252c67f5582)

**Comment by daksh2k** [comment]
For that mode(animated art) there is a minimum value to achieve the desired effect. Otheriwise the background won't work.
