### ISSUE TITLE
[Bug]: Stopped working entirely

### ISSUE THREAD

**Issue by mccalltristan** [daksh2k/Spicetify-stuff#131]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.26.1187.g36b715a1
Spicetify v2.27.2
Theme: Dribbblish / catppuccin-mocha
Extensions: fullAppDisplayMod.js, adblock.js, star-ratings.js, aoty.js, hidePodcasts.js, skipStats.js, imageOpener.js, volumePercentage.js, fullScreenWrapper.js, theme.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

The entire extension just doesn't work, I've tried reinstalling. There just isnt any button to open either the TV mode or regular mode. The extension is installed properly.

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/134766063/156f8206-497e-4ea2-9031-1828623afe68)

**Comment by brokeAK** [comment]
Happening for me as well.

**Comment by aheeres** [comment]
same here unfortunately

**Comment by Daniel1788** [comment]
same for me

**Comment by Ljuder** [comment]
got a similar issue aswell

**Comment by daksh2k** [comment]
Fixed, Just restart/reload Spotify. 
Thanks for reporting!
