### ISSUE TITLE
[Bug]: Album image  not updating

### ISSUE THREAD

**Issue by adambnmohd** [daksh2k/Spicetify-stuff#135]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.25.1011.g0348b2ea
Spicetify v2.29.1
xpui_2023-11-20_1700498575257_0348b2e
cef_118.7.1+g99817d2+chromium-118.0.5993.119
```

### 📝 Description

Album image and title does not update when the song finishes/skipped

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/62837732/0ccf324d-aa08-4280-a692-98022906e52c)

**Comment by adambnmohd** [comment]
same issue after updating and im using the wrapper
Spotify for Windows (64 bit)
1.2.29.605.g66a43ceb
Spicetify v2.30.0
xpui_2024-01-15_1705312536455_66a43ce
cef_120.2.3+g7d89c0c+chromium-120.0.6099.199
Runtime: Alloy

**Comment by daksh2k** [comment]
@adambnmohd can you add a video, it would be very helpful for debugging.

**Comment by adambnmohd** [comment]
@daksh2k
https://github.com/daksh2k/Spicetify-stuff/assets/62837732/0b8434db-5492-439a-b193-4749e3e82485

**Comment by daksh2k** [comment]
Hi @adambnmohd is this issue still occuring?
Forgot to update here, but wasn't able to reproduce it.

**Comment by adambnmohd** [comment]
@daksh2k on version 2.5.0 of the extension, still occuring

**Comment by Fabian-MIA-23** [comment]
@daksh2k Still happening

**Comment by daksh2k** [comment]
Wasn't able to reproduce it, closing.
