### ISSUE TITLE
[Feature Request]: Consistent Lyrics Track Delay

### ISSUE THREAD

**Issue by Dynamixus** [daksh2k/Spicetify-stuff#136]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

I'm using a Bluetooth Speaker and I configured it to have a high buffer around 2 seconds so there's no stuttering issue when I play music. I like having the lyrics on with the Full Screen Mode extension, and I use the delay feature to have the lyrics align properly with the music.

The problem is it resets after every song, so then I have to set the track delay again to make it work. I was hoping for the Track Delay to remain consistent throughout the whole session of Full Screen Mode, instead of it resetting after every song.

**Comment by daksh2k** [comment]
Actually, lyrics are not controlled by this extension, it's provided by the `lyrics-plus` custom app. A better place would be here to raise this issue https://github.com/spicetify/spicetify-cli
