### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Y2KL** [daksh2k/Spicetify-stuff#138]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Save Playlists

### ℹ Environment / Computer Info

```Markdown
windows
```

### 📝 Description

when i click or the tv mode or the fullscreen the whole spotify turn into a gray screen and nothing shows up

### 📸 Screenshots

![Screenshot 2024-02-01 171458](https://github.com/daksh2k/Spicetify-stuff/assets/158513097/fb5f611b-60ba-4000-a33a-14f4976c5224)

**Comment by daksh2k** [comment]
Fixed in https://github.com/daksh2k/Spicetify-stuff/commit/4f4f76a74ef027280ffdc8bae3ca000ac305e440
It's a `spicetify-cli` issue, but added a workaround.
