### ISSUE TITLE
[Bug]:  lyrics dont show and song that had them on fullscreen dont have them anymore

### ISSUE THREAD

**Issue by jaydan0** [daksh2k/Spicetify-stuff#147]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
0.9.4
```

### 📝 Description

song that had lyrics on fullscreen dont have them anymore pls help

### 📸 Screenshots

![Screenshot 2024-02-16 160318](https://github.com/daksh2k/Spicetify-stuff/assets/140856177/044d61b4-e00a-4976-857b-d1dc16a785c3)

**Comment by daksh2k** [comment]
I know it's an issue with `lyrics-plus` extension not working in spotify `1.2.31`, check https://github.com/spicetify/spicetify-cli/issues/2844 for any updates.

**Comment by rxri** [comment]
hiya, `v2.32.0` should fix this issue ^^
