### ISSUE TITLE
[Bug]: Lyrics Plus just showing a loading icon

### ISSUE THREAD

**Issue by AufaDio** [daksh2k/Spicetify-stuff#149]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Other

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.32.1
Theme: marketplace
Extensions: adblock.js, spotifyGenres.js, CoverAmbience.js, queuePanel.js, fullScreenWrapper.js, spiceDL.js
Custom apps: marketplace, stats, lyrics-plus
```

### 📝 Description

Since i was updated latest Spotify update and updated Spicetify twice, v2.32.1 and above it (idk what version was that), my Lyrics Plus only showed a loading icons as you can see below (all of version, not only Genius). I tried to restart Spotify, reset config and restart config, but doesnt fix this bug/issue.

### 📸 Screenshots

![Cuplikan layar 2024-02-22 195253](https://github.com/daksh2k/Spicetify-stuff/assets/84841319/6d00fad5-6d61-4210-9793-622f66087342)

**Comment by daksh2k** [comment]
For me this problem was fixed in `v.2.32.1`
If you are still facing this issue, report it on https://github.com/spicetify/spicetify-cli/issues, as  `lyrics-plus` comes bundled with spicetify.
