### ISSUE TITLE
No lyrics in Full Screen

### ISSUE THREAD

**Issue by DeathkidVR** [daksh2k/Spicetify-stuff#15]
There is no lyrics in the fullscreen option no matter how much I configure it.

### Screenshot

![image](https://user-images.githubusercontent.com/68340789/179861247-1d80b41e-ed69-4dd0-a86f-3162e7d279e2.png)

**Comment by daksh2k** [comment]
Did you follow this [note?](https://github.com/daksh2k/Spicetify-stuff/blob/master/EXTENSIONS.md#note-you-need-lyrics-plus-custom-app-for-showing-lyrics-in-the-extension)

**Comment by DeathkidVR** [comment]
Thank you, no I didn't. Sorry for the trouble!

**Comment by daksh2k** [comment]
No trouble :)
