### ISSUE TITLE
[Bug]: Lyrics not appearing for any song.

### ISSUE THREAD

**Issue by svkqs** [daksh2k/Spicetify-stuff#150]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.30.1135.g02fef27a
Spicetify v2.33.1
```

### 📝 Description

When I go full screen for any song the lyrics will never appear it just gives me the (-_-) face thing and then it goes to the side.

### 📸 Screenshots

<img width="2560" alt="Screenshot 2024-02-29 164221" src="https://github.com/daksh2k/Spicetify-stuff/assets/112209249/bd1177c9-9c49-4e4f-b49e-93f199bae50a">
<img width="2560" alt="Screenshot 2024-02-29 164353" src="https://github.com/daksh2k/Spicetify-stuff/assets/112209249/41b8ebed-c842-4b08-a042-82fb5afb2519">
(notice the little face on the side that's about to swing to the side)

**Comment by Hinols** [comment]
I have the same problem

**Comment by HydroXBR** [comment]
@svkqs and @Hinols, do you have installed the `lyrics-plus` custom app? 

To do it, type `spicetify config custom_apps lyrics_plus` and then `spicetify apply` (in PowerShell).

**Comment by svkqs** [comment]
Yes, I already have lyrics plus installed.

**Comment by shaunbharat** [comment]
I have the same issue. No lyrics when in any full-screen view from this extension, but if I choose pop-up lyrics, they are correct.

**Comment by svkqs** [comment]
This fixed the problem, the lyrics show up now. Thanks, Shaunbharat!

**Comment by shaunbharat** [comment]
No problem! Hopefully it doesn't become an issue again because I still have no idea what caused the lyrics to stop working.
