### ISSUE TITLE
[Bug]: High CPU usage when using Full Screen

### ISSUE THREAD

**Issue by ameliorability** [daksh2k/Spicetify-stuff#151]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Linux (Flatpak) (Fedora) version 1.2.31.1205.g4d59ad7c
Spicetify v2.33.2
Extensions: trashbin.js
Custom Apps: marketplace, lyrics-plus
```

### 📝 Description

Excessively high CPU usage when using Full Screen. This was not an issue in the past, but occurs in the latest FAD update. Occurs in both TV and full screen mode.

Steps: just open Full Screen

That being said, great extension and thank you for making it. I have been using it for several months, it looks so good!

### 📸 Screenshots

When using FAD
![image](https://github.com/daksh2k/Spicetify-stuff/assets/141889580/4e20a057-4536-4448-817b-3281197dc3ec)

When not using FAD
![image](https://github.com/daksh2k/Spicetify-stuff/assets/141889580/043c1d0a-9c29-4875-861d-67e24606f8d2)

**Comment by nxtalex** [comment]
same, hopefully get solved soon

**Comment by daksh2k** [comment]
I think the issue is because of `lyrics-plus`, can you disable lyrics and see if it fixes the issue for now? 
I confirmed on my machine the issue is lyrics, also you can check by going to lyrics from the sidebar, the CPU consumption skyrockets.
Meanwhile, report the issue here https://github.com/spicetify/spicetify-cli/issues

**Comment by nxtalex** [comment]
> I think the issue is because of `lyrics-plus`, can you disable lyrics from the settings and see if it fixes the issue for now? I confirmed on my machine the issue is lyrics, also you can check by going to lyrics from the sidebar, the CPU consumption skyrockets. Meanwhile, report the issue here https://github.com/spicetify/spicetify-cli/issues, as I have no control over the lyrics.

i took off every lyrics extension i had but it still uses around 20% cpu, as soon as i get off full screen it goes to 0 and uses just ram

**Comment by nxtalex** [comment]
by the way, the cpu usage is very high also for songs without lyrics, this means the problem is not with the lyrics unless you still enable the lyrics extensions when there are none

**Comment by ameliorability** [comment]
Thanks for the input, lyrics-plus is indeed the culprit but WHEN used with full screen.
Using lyrics-plus: 
![image](https://github.com/daksh2k/Spicetify-stuff/assets/141889580/02316b0e-6038-4a60-8b13-2ebc467ad6d2)

CPU usage spikes when lyrics-plus is being used. Thank you for the help and for the wonderful extension.
