### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Janamen** [daksh2k/Spicetify-stuff#153]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Other

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (32 bit)
1.2.26.1187.g36b715a1
Spicetify v2.33.2
Theme: Default Dynamic / Base
Extensions: songstats.js, beautiful-lyrics.js, fullScreenWrapper.js, playEnhancedSongs.js, playlist-icons.js, romaja_lyrics.js, loopyLoop.js, immersiveView.js, shuffle+.js, fullAppDisplay.js, romaji_lyrics.js, popupLyrics.js, quickQueue.js, quick-add-to-playlist.js, noControls.js, default-dynamic.js, Vibrant.min.js
Custom apps: marketplace, lyrics-plus, new-releases
```

### 📝 Description

I've got a vertical display, 1100x3840, yet the vertical monitor support option doesn't detect this and the lyrics stay centered and in landscape mode. Perhaps it needs a switch instead rather than detection? I tried turning off fullscreen but they were still centered.

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/88746002/d127f620-54a4-4ac2-b085-f31b3ac3f21e)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/88746002/c716df6d-54ff-45b2-9cf5-5b26374b20c9)

**Comment by daksh2k** [comment]
Vertical monitor support is not for TV mode, it's there for default mode only.
