### ISSUE TITLE
[Bug]: Top Bar component not available

### ISSUE THREAD

**Issue by DonPingus** [daksh2k/Spicetify-stuff#154]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.33.1039.g8ddb5918
Spicetify v2.35.1
```

### 📝 Description

The extension won't load at all and says the top bar component is not available. Lyrics-plus is active and everything but when I click fullscreen it's just the default spotify one. I also get the error that the top bar component is not available.

### 📸 Screenshots

![fullscreen](https://github.com/daksh2k/Spicetify-stuff/assets/74151712/585cddb4-0c8b-4407-afba-ccaa7b3553a0)

**Comment by daksh2k** [comment]
Weird, don't have this issue, and I am on the same version,

can you run `spicetify enable-devtools` in terminal
and inside spotify open console by `ctrl+shift+i`

then paste and run this in console
`document.querySelector(".main-topBar-historyButtons")` 
and share what you get? also add screen shot of the spotify. 

<img width="795" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/bf4b33cb-45e4-4fee-b057-0b5e031f38e0">

**Comment by DonPingus** [comment]
![image](https://github.com/daksh2k/Spicetify-stuff/assets/74151712/532d2de0-1087-4196-857d-c4f6a8865397)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/74151712/c4f206e9-4600-442f-bde9-b87417e9390c)


> Weird, don't have this issue, and I am on the same version,
> 
> can you run `spicetify enable-devtools` in terminal and inside spotify open console by `ctrl+shift+i`
> 
> then paste and run this in console `document.querySelector(".main-topBar-historyButtons")` and share what you get? also add screen shot of the spotify.
> 
> <img alt="image" width="795" src="https://private-user-images.githubusercontent.com/42179185/315954428-bf4b33cb-45e4-4fee-b057-0b5e031f38e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExMDIzOTAsIm5iZiI6MTcxMTEwMjA5MCwicGF0aCI6Ii80MjE3OTE4NS8zMTU5NTQ0MjgtYmY0YjMzY2ItNDVlNC00ZmVlLWIwNTctMGI1ZTAzMWYzOGUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDEwMDgxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0MThkNTcxYTQwNTNmZjkxOWUyNGI2Yzc2ZWE1MTg5YTJiM2MzM2ZjNThiYTQ4OTE1N2I2M2Q1MzU3OWZhMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K0D-Ru_UOnUDKoS-bMjkO42cDg-V_OEliwrniAIY2mY">

**Comment by DonPingus** [comment]
Nope everything is default hopefully they roll out this version of spotify soon none of the extensions work and that's probably why lol

**Comment by XanoPhobious** [comment]
This is because the "Show global nav bar with home button, search input and user avatar" (in experimental feature) set to anything else other than "control".

**Comment by daksh2k** [comment]
@DonPingus extension should be unblocked now, you can use the keyboard shortcut `T` to activate the TV mode,  default mode will work with both the button and kbd shortcut.
I will re-add the button for TV Mode on topbar as this UI gets rolled out.

**Comment by EDM115** [comment]
@daksh2k the global navbar UI is the default as of 1.2.46 and the experimental setting can't be set back to control

**Comment by daksh2k** [comment]
Okay thanks @EDM115 
I'll add support for the button on new ui as well.

**Comment by daksh2k** [comment]
This is added.
