### ISSUE TITLE
[Feature Request]: Option to change cover art corner radius

### ISSUE THREAD

**Issue by Joecalone** [daksh2k/Spicetify-stuff#157]
### Choose the extension for feature request.

Other

### 📝 Provide a description of the new feature

I'm not very tech-savvy, so maybe there's an easy way of doing this, but I tried editing the fullAppDisplay.js file to no avail:

I'm not a big fan of rounded corners on album art, so it would be nice to be able to set the corner radius to 0px. If there's a way of currently doing this, I'd be very grateful if you could point me towards it. Thanks.

**Comment by daksh2k** [comment]
Hi @Joecalone, There is no option in settings to this currently from settings but you can override the styles via CSS.

First, check you have installed the correct extension, mine is this one
<img width="197" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/c03ce4fd-7acc-4e79-bdb4-bf259c5bfdff">


you can add your custom CSS by using this extension
<img width="225" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/29911fdf-070a-4846-b4b7-41a11a26fd59">

open the CSS editor by f12 or by going to the settings
and
paste this style
```css
#fsd-art-image{
  border-radius: 0px !important;
}
```

<img width="977" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/905329e4-9703-4560-afa1-e8b2ec8b3170">

Then it should work.

**Comment by Joecalone** [comment]
This worked perfectly, thanks so much!
