### ISSUE TITLE
[Feature Request]: esc to home

### ISSUE THREAD

**Issue by Neondroidd** [daksh2k/Spicetify-stuff#158]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

The extension [fullscreen](https://github.com/daksh2k/Spicetify-stuff/tree/master/Extensions/full-screen) when the esc button is pressed, it immediately exits fullscreen and goes straight to home instead of exiting fullscreen to windows mode

**Comment by daksh2k** [comment]
This was added in v2.7.0
