### ISSUE TITLE
[Bug]: Artist Artwork not showing in Full Screen Mode

### ISSUE THREAD

**Issue by PasttaTypo** [daksh2k/Spicetify-stuff#162]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit) 1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Extensions:
autoSkipExplicit.js
autoSkipVideo.js
bookmark.js
fullAppDisplay.js
keyboardShortcut.js
loopyLoop.js
popupLyrics.js
shuffle+.js
trashbin.js
webnowplaying.js
```

### 📝 Description

Artist artwork not displaying in full screen or TV mode, instead shows album art instead. Changing between "artist artwork" and "album art" in background choice settings makes no difference.
On Spotify's default full-screen view, the artist artwork is displayed in background.

**Comment by samuelawachie** [comment]
This bug is still present. I'd been noticing it over the past week, and just assumed it'll rectify itself but no luck. I was on an older version of spicetify due to another bug with the misaligned sidebar entries on the left (x.34.1), but then updated to the latest version just to make sure this hasn't been patched out recently. But still the same behavior on my preferred version as well as the latest version.

**Comment by samuelawachie** [comment]
Well, I'm on Linux Zorin 17.1, Spicetify 2.34.1/2.36.12, Spotify version (latest allowed to use the old UI(will check the exact version number soon)). 
This just started being a problem about a week ago, as I've said. It was fine before.

**Comment by samuelawachie** [comment]
I suppose I'm the only one having the bug then? Hi @daksh2k  could you check this out again please? It appears you're the only person in a position to do something about this.

**Comment by daksh2k** [comment]
Hi have been a little busy lately, 
but seems like your spotify is a little old, if you can try updating, it might solve the problem.
I'll add a fix which will work on older versions if I get time.

**Comment by samuelawachie** [comment]
> Hi have been a little busy lately, but seems like your spotify is a little old, if you can try updating, it might solve the problem. I'll add a fix which will work on older versions if I get time.
I was on the latest version of spotify. But some things were not working, like bookmark, shuffle+ and playlist radio. And I wanted that old UI, as I can't stand the new UI. This was the latest version of spotify that was available (I looked EVERYWHERE) that was still capable of having the old UI using SpotX. 
And I notice that all those JS plugins work well on it. Playlist radio is there. Enhance is there. Everything. And my favorite UI. It was just so perfect for weeks, until I started noticing this Artist Artwork thingy.
Please, could you do the fix as soon as possible? I actually can't do much listening except with this fullscreen app when I'm on my laptop. It's been keeping the music and I separated over the last few days now (and we need each other) :')
What God has joined together, let no bug put asunder. (:

**Comment by Delusoire** [comment]
> I actually can't do much listening except with this fullscreen app when I'm on my laptop.

You should still be able to use an [old version](https://raw.githubusercontent.com/daksh2k/Spicetify-stuff/4009d3388592def82f2b12edd74a5238b738a243/Extensions/full-screen/dist/fullScreen.js) of the extension and it would work for you. Just grab the file I linked and enable it manually with the `spicetify` cli.

**Comment by samuelawachie** [comment]
> > I actually can't do much listening except with this fullscreen app when I'm on my laptop.
> 
> You should still be able to use an [old version](https://raw.githubusercontent.com/daksh2k/Spicetify-stuff/4009d3388592def82f2b12edd74a5238b738a243/Extensions/full-screen/dist/fullScreen.js) of the extension and it would work for you. Just grab the file I linked and enable it manually with the `spicetify` cli.
>
Perhaps you misunderstood. The extension is working. What isn't working is the background image is always using Album art, when Artist Art is what is selected in the options. Will installing the JS file you linked solve that issue?

**Comment by Delusoire** [comment]
It will. The bug fix introduced in the latest commit broke the code for fetching the authorization token for older Spotify versions.

**Comment by Delusoire** [comment]
By the way, since you're not updating your spotify version again, you should consider installing all your extensions (and themes) locally to reduce the risk of things breaking in the future.

**Comment by samuelawachie** [comment]
> By the way, since you're not updating your spotify version again, you should consider installing all your extensions (and themes) locally to reduce the risk of things breaking in the future.
>
Oh I see. I'll start on those right away. Please do hang around for a while, in case I run into any problems. Thanks mate

**Comment by samuelawachie** [comment]
> By the way, since you're not updating your spotify version again, you should consider installing all your extensions (and themes) locally to reduce the risk of things breaking in the future.
>
I'm already needing help. How do I install these extensions locally? I can't find them anywhere to then download and save in .config/spicetify/Extensions or .config/spicetify/CustomApps
The themes are available locally now. But the relevant part of my config.xpui.ini shows
extensions = trashbin.js|bookmark.js|shuffle+.js
custom_apps = marketplace|new-releases|lyrics-plus|reddit
Where do I download these? I can't see them anywhere

**Comment by samuelawachie** [comment]
> > > I actually can't do much listening except with this fullscreen app when I'm on my laptop.
> > 
> > 
> > You should still be able to use an [old version](https://raw.githubusercontent.com/daksh2k/Spicetify-stuff/4009d3388592def82f2b12edd74a5238b738a243/Extensions/full-screen/dist/fullScreen.js) of the extension and it would work for you. Just grab the file I linked and enable it manually with the `spicetify` cli.
> 
> I just downloaded that, and installed it manually. I don't know if it replaced the other one I had, but it's not yet showing the artist art. Nothing looks changed. I also got the extensions and custom apps locally now after cloning the repo, but I don't know if it's using the local ones or the (remote?) ones I was using before. I put them in the extensions / custom_apps folders as the case may be, and applied them. But I just don't know what it's using now. I un-applied the former ones first before applying again (after inserting them in the folders)
>
It appears that the one I was using was installed from the marketplace (in-app). When I uninstalled that one, this one wouldn't even show up. Trying to find a way ... No other extension I was using was installed from the in-app marketplace, except this one. I don't know why it isn't coming up after uninstalling that one, and installing this one manually. All the other extensions installed manually are showing up as usual.

**Comment by samuelawachie** [comment]
I finally got the extension to show up. But the one you sent me is still doing the same thing. The file is also dramatically smaller.
The original one on this repo is 212.4 kB while this one is 61.8 kB. Is there any way I can get the previous version of this here? They should be similar in size, right?

**Comment by samuelawachie** [comment]
> > The original one on this repo is 212.4 kB while this one is 61.8 kB.
> 
> On my side, both files are 208kb in size. Try `curl`ing the URL directly.
>
I finally got it to work. I worked my way through the different versions on this repo, using the history function. Had to go back to the version from 3 months ago. That was the latest version that worked. 
At least now, I won't be surprised by any " non user-initiated" update to my extensions seeing as my use-case and config is much different to almost any other person out there. So that's a good benefit from this whole process.
Thanks for pointing me in the right direction.

**Comment by daksh2k** [comment]
Oh a little late to the party
I added a fix https://github.com/daksh2k/Spicetify-stuff/commit/e16e54e8463270e636ba4353170b222e10661600 which should be backward compatible, but yeah I'll recommend the same thing as keeping the extensions locally if you are using old Spotify versions
[Readme ref](https://github.com/daksh2k/Spicetify-stuff?tab=readme-ov-file#method-3manual-updates-manual)
Thanks @Delusoire for the help.
