### ISSUE TITLE
Remove Glow Effect in lyrics on full screen mode.

### ISSUE THREAD

**Issue by Chingman12** [daksh2k/Spicetify-stuff#166]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

i would like to disable the glow effect on full screen mode lyrics and move the lyrics to the center of the screen .
![Screenshot (22)](https://github.com/daksh2k/Spicetify-stuff/assets/168269490/56527ce4-7d1f-4f76-bb3a-bf9869cde31e)

**Comment by daksh2k** [comment]
Hi, no glow effect is added by this extension, it might be your theme or the default lyrics-plus, You can disable blur from lyrics settings from here.

<img width="715" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/c2a38365-413f-4858-a0a0-0ae839c0da1f">
