### ISSUE TITLE
[Bug]: Lyrics disappear after half a second.

### ISSUE THREAD

**Issue by mccalltristan** [daksh2k/Spicetify-stuff#167]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.40.599.g606b7f29
Spicetify v2.36.13
Theme: Ziro / gray-dark
Extensions: adblock.js, hidePodcasts.js, skipStats.js, imageOpener.js, volumePercentage.js, fullScreenWrapper.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

1. Lyrics work through Lyrics-Plus page. 
2. Open fullscreen or TV mode.
3. Lyrics will appear for ~1 second then disappear.
4. The space for the lyrics does not close as well, it just stays as in photo 2.

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/134766063/384fc582-3c11-414c-9c59-145ea285071a)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/134766063/dbce0e29-cd07-4fc2-8c9b-e6e864daf6af)

**Comment by DarkVibes1x** [comment]
i also have been having this issue ever  since the new dist of fullScreen

**Comment by daksh2k** [comment]
Can you enable this setting from the experimental features, 
<img width="594" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/d8735d25-dc14-409c-b2fb-cdb460393adb">

**Comment by SergioUnoxx** [comment]
![image](https://github.com/daksh2k/Spicetify-stuff/assets/67900766/5c9f56cb-0b0e-4fc3-bc95-9343f0970fff)
![image](https://github.com/daksh2k/Spicetify-stuff/assets/67900766/90819cad-dc6c-4cfb-a8cb-884c1493c2b1)

Hi, I have the same problem and I just tested the "Queue on the right panel" experimental feature. The lyrics do appear now, but the queue button is replacing the Lyrics Plus one

**Comment by daksh2k** [comment]
Yep that's intended, you can still use the keyboard shortcut "L" to quickly toggle lyrics and "Q" for the queue.

**Comment by DarkVibes1x** [comment]
> Can you enable this setting from the experimental features, <img alt="image" width="594" src="https://private-user-images.githubusercontent.com/42179185/344589556-d8735d25-dc14-409c-b2fb-cdb460393adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDA0MDUsIm5iZiI6MTcxOTg0MDEwNSwicGF0aCI6Ii80MjE3OTE4NS8zNDQ1ODk1NTYtZDg3MzVkMjUtZGMxNC00MDljLWIyZmItY2RiNDYwMzkzYWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDEzMjE0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NTlmZjlhY2ViMmE1MDcwNGNjYjdjMmIyMzRiMzNkZjA5MGNiZWE5MmViZjJhMDE5OWFkNmJkYzE1ODlhYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.grtwY8FUebSV-KELmIib47IrrEljXwg_W5sfFZEjkbc">

yep this works like a charm ty

**Comment by FreverZ** [comment]
I can't find the Experimental Features tab, where can I find it ?

**Comment by mccalltristan** [comment]
> Can you enable this setting from the experimental features, <img alt="image" width="594" src="https://private-user-images.githubusercontent.com/42179185/344589556-d8735d25-dc14-409c-b2fb-cdb460393adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyNTE4MjAsIm5iZiI6MTcyMDI1MTUyMCwicGF0aCI6Ii80MjE3OTE4NS8zNDQ1ODk1NTYtZDg3MzVkMjUtZGMxNC00MDljLWIyZmItY2RiNDYwMzkzYWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA2VDA3Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhZWRlZjYzOGJmM2Q5M2JjMTg4NzNkMjM2ZjI0NWNjZTFlNjA0MzU4OGZkZDVmOWRlNDhlZGEyNzIzYjg4ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ggbRLzbekPzE-HL8t0PTU2dm3ePJkAabkixLNb_2fSU">

Worked for me thanks

**Comment by FoxyLoon** [comment]
Well, with the possibility of having the Queue on the right side of the screen, I have a problem where the Queue now overlaps the “Upnext”:
![Screenshot](https://github.com/user-attachments/assets/2f100f92-d207-4a51-a907-7b961103acff)

Suggestion 1: Would it be possible to make the Queue smaller vertically to make room for the “upnext”? 

Suggestion 2: Visually, I think it would be a good idea to make the middle section (where it shows the cover, title, artist, etc...) also to the left so that it is symmetrically the same as it was with the Lyrics, and also, to center the Queue between the middle of the screen and the right side of the screen (just like the Lyrics when it is centered on the right side of the screen).

Suggestion 3: With a little tweaking, I think it would be possible to organize and display the 3 sections on the screen. For example, the Queue on the right, the Lyrics on the left and the rest in the middle. The Lyrics and the Queue could also be in opposite places.

**Comment by fernamp** [comment]
Still a thing. And the "Q" just make the queue appears but there are no lyrics.
Changed themes and nothing works.

Spotify for Windows (64 bit)
1.2.53.438.g246d60c9
Spicetify v2.38.7
Theme: Hazy / Base
Extensions: fullScreenWrapper.js, hazy.js
Custom apps: marketplace, lyrics-plus

**Comment by wartles** [comment]
where is this setting at? i cant find it when right clicking the extension

> Can you enable this setting from the experimental features, <img alt="image" width="594" src="https://private-user-images.githubusercontent.com/42179185/344589556-d8735d25-dc14-409c-b2fb-cdb460393adb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDIzOTIyNjEsIm5iZiI6MTc0MjM5MTk2MSwicGF0aCI6Ii80MjE3OTE4NS8zNDQ1ODk1NTYtZDg3MzVkMjUtZGMxNC00MDljLWIyZmItY2RiNDYwMzkzYWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzE5VDEzNDYwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5YWZiZjM4ZmFlYTcwZTZkODIxOTZkOGZjYmNiYTYwYmYxMDdlODFlMzE3MjcyNjFkYjkxODdmMDlmOGY2ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CvED1N4W-PFdkBsECLcwN09058vkoAYyRWivRjzDcbU">
