### ISSUE TITLE
[Bug]: TOP RIGHT 3 BUTTON  ISSUE

### ISSUE THREAD

**Issue by Aseem-ibn-imthiyas** [daksh2k/Spicetify-stuff#169]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.40.599.g606b7f29
Spicetify v2.36.13
Theme: Lucid / dark
Extensions: adblock.js, fullScreenWrapper.js, theme.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

I'm using your extension 

its very realistic and very comfortable to use 
thanks for this 

and notice some issue with extension 

when i toggle full screen top right 3 button (minimize, full screen, close button are look different from full screen aesthetic and its look like scratch in car)

please update the solution asap

thanks ❤️ 

### 📸 Screenshots

![Screenshot 2024-07-03 204629](https://github.com/daksh2k/Spicetify-stuff/assets/173438871/fa1466ff-8727-413e-a33d-b3608c3089d2)

**Comment by daksh2k** [comment]
Hi @Aseem-ibn-imthiyas, this is your theme issue.
