### ISSUE TITLE
[Bug]: A second Full Screen button

### ISSUE THREAD

**Issue by LunarGhost** [daksh2k/Spicetify-stuff#17]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.91.824.g07f1e963
- Spicetify version: 2.11.1
```

### 📝 Description

When I installed the Full Screen extension it added a second full screen button.

Other then that the extension still works as intended. 

### 📸 Screenshots

![6uyiku](https://user-images.githubusercontent.com/554851/184676875-ac1e77e3-f5a4-4fb5-bcbc-cbab121b1e4e.png)

**Comment by daksh2k** [comment]
Actually that's intended behaviour, the default one is added by spotify just for Spotify Premium users, I added mine with a different icon to differentiate from the spotify one.

If you want you can hide the Spotify one but that would require a little knowledge of `CSS`.

**Comment by LunarGhost** [comment]
Alright, Thank you.

I know nothing about CSS.
