### ISSUE TITLE
[Bug]: occurs when installing lyrics plus

### ISSUE THREAD

**Issue by MEModdvvd** [daksh2k/Spicetify-stuff#170]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Other

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.40.599.g606b7f29
Spicetify v2.36.14
Theme: Catppuccin / frappe
Extensions: adblock.js, fullAlbumDate.js, sortByPlayCount.js, listenTogether.js, lastfm.js, extractor.js, playNextWrapper.js, QueueTime.js, imageOpener.js, show-the-genres.js, SleepTimer.js, group-session.js, toggleFriendActivity.js, wikify.js, writeify.js, phraseToPlaylist.js, playlistIntersection.js, goToSong.js, skipStats.js, savePlaylistsWrapper.js, playOnYouTube.js, spotifyBackup.js, playEnhancedSongs.js, playlist-icons.js, copytoclipboard.js, tracksToEdges.js, copy-lyrics.js, resume-playlist.js, playRandom.mjs, cat-jam.js, immersiveView.js, quickQueue.js, sleepTimer.js, spotifyGenres.js, playbarClock.js, extended-copy.js, volumePercentage.js, skip-after-timestamp.js, startup-page.js, full-queue-clear.js, discography-to-playlist.js, remove-unplayable-songs.js, spotispy.js, autoplay.js, LuckyLP.js, fullScreenWrapper.js, theme.js
Custom apps: marketplace, lyrics-plus, new-releases
```

### 📝 Description

this error happened when installing  lyrics plus

### 📸 Screenshots

![Desktop Screenshot 2024 07 05 - 04 19 54 65](https://github.com/daksh2k/Spicetify-stuff/assets/174756809/a8f9e69a-0b67-4be9-861d-755dce00c7cf)

**Comment by daksh2k** [comment]
lyrics-plus is already installed as per the logs, no issues there.
