### ISSUE TITLE
[Bug]: Queue toggle button is covered when queue is shown on vertical monitor

### ISSUE THREAD

**Issue by pumkinisawesome** [daksh2k/Spicetify-stuff#172]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for macOS (Apple Silicon)
1.2.41.434.g39a25e2c
Spicetify v2.36.14
Theme: Better-Bloom / darkgreen
Extensions: fullScreenWrapper.js, oldCoverClick.js, theme.js
Custom apps: marketplace, better-local-files, ncs-visualizer, lyrics-plus
```

### 📝 Description

I've seen a lovely new queue button (at least it seems new because I haven't noticed it before) to the right hand side of the play controls buttons, which allows the queue to be shown while in fullscreen mode. However, when being used on a vertical monitor, the queue actually covers that button, so there isn't any way to minimise the queue again without exiting fullscreen mode. This can be seen in the attached screenshot. 

I was wondering if there might be a way to either shift the play information to the left so that it is still visible next to the queue, or if another queue minimisation button could be added at the top right of the queue window itself or something?

Thank you!

### 📸 Screenshots

![CleanShot 2024-07-05 at 18 04 27](https://github.com/daksh2k/Spicetify-stuff/assets/82690916/99d1d6e6-fc05-4cb6-ad32-504bf1b93d8e)

**Comment by daksh2k** [comment]
Ahh lol didn’t test it out on vertical mode, it's a rough draft, will take a while to polish the UI though. 
Thanks for pointing it out.

Meanwhile, there is the keyboard shortcut <kbd>Q</kbd>, which you can use to toggle it.

**Comment by pumkinisawesome** [comment]
Ah wonderful, thank you!

**Comment by AstudilloMarillo** [comment]
Would be neat if it'd hide when you leftclick anywhere outside the queue.

**Comment by daksh2k** [comment]
Should not be an issue anymore, reduced the width of queue panel in vertical mode.
