### ISSUE TITLE
[Bug]: i cant put lyrics in big in TV mode like before

### ISSUE THREAD

**Issue by hugoorc** [daksh2k/Spicetify-stuff#173]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.41.434.g39a25e2c
Spicetify v2.36.14
```

### 📝 Description

When I turn on the TV mode or the other, the letter on the right does not appear large as before, I can only see it if I open a new sidebar, which is why I cannot see it as large as before.

### 📸 Screenshots

![Screenshot 2024-07-07 040941](https://github.com/daksh2k/Spicetify-stuff/assets/150565884/0de7ab6d-d658-4c76-afb6-7966b05d636a)

**Comment by daksh2k** [comment]
Should be fixed in v2.7.0
