### ISSUE TITLE
lyrics not showing up on full screen mode

### ISSUE THREAD

**Issue by saaraffe** [daksh2k/Spicetify-stuff#174]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.41.434.g39a25e2c
Spicetify v2.36.14
Theme: Hazy / Base
Extensions: fullScreenWrapper.js, romaja_lyrics.js, fullAppDisplayMod.js, theme.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

i click on full screen mode, the lyrics appear for a split second on the right side and dissapear.

### 📸 Screenshots

Uploading Spotify Premium 2024-07-09 00-32-39.mp4…

**Comment by NahuenL** [comment]
same issue here

**Comment by daksh2k** [comment]
@NahuenL @saaraffe 
check this https://github.com/daksh2k/Spicetify-stuff/issues/167#issuecomment-2199480598
