### ISSUE TITLE
[Bug]: Lyrics not working.

### ISSUE THREAD

**Issue by Neekodesu** [daksh2k/Spicetify-stuff#175]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Save Playlists

### ℹ Environment / Computer Info

```Markdown
Spotify para Windows (64 bits)
1.2.41.434.g39a25e2c
Spicetify v2.36.14
Theme: marketplace
Extensions: hidePodcasts.js, tracksToEdges.js, playlist-icons.js, imaged-folders.js, playOnYouTube.js, autoSkipVideo.js, bookmark.js, popupLyrics.js, spotifyGenres.js, volumePercentageWrapper.js, fullScreenWrapper.js, adblock.js
Custom apps: marketplace, lyrics-plus, new-releases
```

### 📝 Description

Simply lyrics won't show, they show for like 0.5 seconds and then dissapear. Neither fullscreen or TV mode

**Comment by daksh2k** [comment]
@Neekodesu check this
https://github.com/daksh2k/Spicetify-stuff/issues/167#issuecomment-2199480598
