### ISSUE TITLE
Lyrics Missing on Dekstop and TV Mode[Bug]: 

### ISSUE THREAD

**Issue by NajaBasit** [daksh2k/Spicetify-stuff#178]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Other

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.41.434.g39a25e2c
Spicetify v2.36.15
Theme: marketplace / dark
Extensions: phraseToPlaylist.js, adblock.js, fullAlbumDate.js, volumePercentageWrapper.js, playEnhancedSongs.js, spotifyGenres.js, SleepTimer.js, group-session.js, CoverAmbience.js, seekSong.js, QueueTime.js, djinfo.js, webnowplaying.js, popupLyrics.js, shuffle+.js, fullScreenWrapper.js
Custom apps: marketplace, lyrics-plus
```

### 📝 Description

When I tried to run Spotify in full-screen mode, the lyrics wouldn't show up. I tried to reinstall the extensions, Lyrics Plus, and even Spotify itself. But the trouble still exists. The lyrics are shown when you open lyrics tab, but not in full screen. This never happened before.

### 📸 Screenshots

![Screenshot (162)](https://github.com/user-attachments/assets/af8c0078-86ab-4182-a58f-96ee2a80ec0d)
![Screenshot (163)](https://github.com/user-attachments/assets/b04e4e91-dd06-43d2-96c7-aaeb57c00742)
![Screenshot (164)](https://github.com/user-attachments/assets/2a3e3846-54d8-4c55-ab25-def554fae41b)

**Comment by uugaabuugaa** [comment]
Same issue here. I have a desktop and a laptop with same spotify and spicetify settings and versions even including firewall settings. It works on the laptop but not on the desktop for some reason. On the desktop the lyrics on right hand side show up for about half a second before disappearing immediately.

Also btw there's no title for the issue. OP should add a title.

**Comment by daksh2k** [comment]
@uugaabuugaa @NajaBasit  check this
https://github.com/daksh2k/Spicetify-stuff/issues/167#issuecomment-2199480598
