### ISSUE TITLE
[Bug]: Lyrics button is gone in Full Screen mode

### ISSUE THREAD

**Issue by AstudilloMarillo** [daksh2k/Spicetify-stuff#179]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.42.290.g242057a2
Spicetify v2.36.15
```

### 📝 Description

There was a button to show/hide lyrics before in Full Screen mode but it's gone now. Using 'L' still works but I really want the button as well. Can it be returned? At least as an option?

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/e8388ba7-fd00-4dd3-8972-d7650d05e8a5)

**Comment by daksh2k** [comment]
Check this
https://github.com/daksh2k/Spicetify-stuff/issues/167#issuecomment-2199480598

**Comment by AstudilloMarillo** [comment]
> Check this [#167 (comment)](https://github.com/daksh2k/Spicetify-stuff/issues/167#issuecomment-2199480598)

Yes I've seen that, but that doesn't make the Lyrics button re-appear. I would really like it back.

**Comment by daksh2k** [comment]
If you want queue as a button you can enable that from settings, by default it's false and lyrics button is shown. In v2.7.0

**Comment by AstudilloMarillo** [comment]
why can't we have both as a button?

**Comment by daksh2k** [comment]
The lyrics button doesn't have that much functionality, if you want to turn off lyrics you can do that from config/settings with 1 extra click, if you quickly want to toggle there is a kbd shortcut `L`.  There'll be too many buttons, it doesn't look good and creates confusion. 

Maybe in the future, there'll be scope for customizing which buttons you want to show in the extra bar.
