### ISSUE TITLE
[Feature Request]: "Radio Edit" Songs

### ISSUE THREAD

**Issue by Zzeyy** [daksh2k/Spicetify-stuff#18]
### Choose the extension for feature request.

Auto Skip

### 📝 Provide a description of the new feature

Add an option to skip (and maybe play the Em' version instead) censored/radio version of songs.

**Comment by daksh2k** [comment]
Can you elaborate what are censored version of songs?
Like you mean songs which do not have an explicit tag?
Maybe share some examples with links so I can fully understand waht you mean.
Otherwise I think it's out of scope of the extension if I understand correctly.

**Comment by Zzeyy** [comment]
Censored / radio version of a song https://open.spotify.com/track/1NOgYyLQJpQ9Ntyn5GnRjr?si=52199e70015241af
Explicit version of a song https://open.spotify.com/track/0fGh0trRN1xz3s41r7V5ce?si=50d5de6cae5e4d0a

Skipping every non-explicit song would result in chaos.
Maybe only skipping songs that have certain words in their name is the best option.

**Comment by daksh2k** [comment]
Added in the latest update.
Also added the ability to auto-play their original songs also for most skipping categories.

**Comment by Zzeyy** [comment]
Ayo, thanks a lot.
