### ISSUE TITLE
[Bug]: Window Control Buttons not visible in full screen mode

### ISSUE THREAD

**Issue by deb12378** [daksh2k/Spicetify-stuff#180]
### 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?

- [X] I have confirmed that I am using the latest versions.

### 🔍 Have you checked for an existing issue?

- [X] I have checked existing issues, both open and closed.

### 🔍 Have you reviewed pinned issues?

- [X] I have reviewed the pinned issues.

### Select the relevant extension for this bug report.

Full Screen Mode

### ℹ System Information

```Markdown
Spotify for Windows (64 bit) 1.2.41.434.g39a25e2c
Spicetify v2.36.15
Extensions: adblock.js, fullScreenWrapper.js, theme.js
Custom apps: lyrics-plus, new-releases, reddit
```

### 📝 Bug Description

Window Control Buttons are not visible in full screen mode. Although they are present at their respective positions on the top right, and clicking on them work, they are not visible and it would be great if they were visible too.

### 📸 Screenshots

While in full screen mode, the controls disappear like this (look at the top right, no minimize, maximize or close buttons visible)

![Screenshot (138)](https://github.com/user-attachments/assets/0cc5c3f7-6a7f-445e-855a-afcff6c0db36)

But I need it to be something like this instead (minimize, maximize, close buttons visible and blended in with the background)

![image](https://github.com/user-attachments/assets/6d363a13-26ee-4e82-a3a7-9f0f0aeaed5e)

**Comment by daksh2k** [comment]
You can disable fullscreen from the settings
<img width="605" alt="image" src="https://github.com/user-attachments/assets/96c581b0-6644-4eef-9269-7403cdcabaa7">

**Comment by deb12378** [comment]
@daksh2k  I believe this issue should be reopened because my problem has not been resolved and no useful information has been provided to help. Here are the details of the ongoing problem: 

I can see that turning off the fullscreen toggle from settings brings the window controls back but I had already solved that problem with the help of a fellow collaborator who had worked on a custom spotify theme named Lucid, but the main issue here is that I want the controls to be VISIBLE as well as PROPERLY BLENDED IN with the background. But as you can see there's a rectangular area on the top right with the controls which doesn't blend in with the background.

Please also do refer to the issue that I had raised here for better understanding of the problem:
https://github.com/sanoojes/Spicetify-Lucid/issues/49

![Screenshot (139)](https://github.com/user-attachments/assets/27449a0a-0bfe-4577-8dbc-bdb272a051a3)

 
Thank you!
