### ISSUE TITLE
[Bug]: lyrics is not showing up

### ISSUE THREAD

**Issue by mrveeeeeeel** [daksh2k/Spicetify-stuff#181]
### 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?

- [X] I have confirmed that I am using the latest versions.

### 🔍 Have you checked for an existing issue?

- [X] I have checked existing issues, both open and closed.

### 🔍 Have you reviewed pinned issues?

- [X] I have reviewed the pinned issues.

### Select the relevant extension for this bug report.

Full Screen Mode

### ℹ System Information

```Markdown
Spotify for Windows (64 bit)
1.2.42.290.g242057a2
Spicetify v2.36.15
```

### 📝 Bug Description

the lyrics is not showing up,when i opened the full screen mode it just doesnt appear

### 📸 Screenshots

![Screenshot 2024-07-20 121711](https://github.com/user-attachments/assets/d939197c-f0dc-40f8-8dd2-ecb623a1e9cc)

**Comment by daksh2k** [comment]
Should be fixed, if you want queue in sidebar panel and lyrics both, enable it from the settings.
