### ISSUE TITLE
[Feature Request]: Change volume on scroll

### ISSUE THREAD

**Issue by Crazy-Unicooorn** [daksh2k/Spicetify-stuff#182]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

I don't think the scroll is associated to an action in Full Screen Mode.
We could add an option to change the volume while scrolling.

### ➕ Additional Information

I like the smart volume bar display feature, but I sometime find myself wanting to change the volume, and the clicking area is so annoying, it would really make it easier if I could just scroll up/down for the volume to adjust up/down. No matter where my mouse is pointing at!

**Comment by daksh2k** [comment]
It'll create a lot of confusion, scrolling is needed for lyrics also.
You can use keyboard shortcuts extension to use arrow keys for volume and progress.
