### ISSUE TITLE
[Feature Request]: Lyric Video Generator

### ISSUE THREAD

**Issue by Phymiu** [daksh2k/Spicetify-stuff#187]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

I'm thinking about how to use this plug-in to make a lyrics video, use the dynamic cover background, upload my own song cover and mp3 to make a lyrics video.

**Comment by daksh2k** [comment]
Hi, you can play local songs on Spotify, album art is directly in the song file it will take that, and lyrics can also be loaded from a file, can be achievable but probably a very niche usecase of this extension. 
Good luck !
