### ISSUE TITLE
[Bug]: Podcast Artist Shows as "Undefined" in Full-Screen Mode

### ISSUE THREAD

**Issue by PasttaTypo** [daksh2k/Spicetify-stuff#192]
### 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?

- [X] I have confirmed that I am using the latest versions.

### 🔍 Have you checked for an existing issue?

- [X] I have checked existing issues, both open and closed.

### 🔍 Have you reviewed pinned issues?

- [X] I have reviewed the pinned issues.

### Select the relevant extension for this bug report.

Full Screen Mode

### ℹ System Information

```Markdown
Spotify for Windows (64 bit)
1.2.45.454.gc16ec9f6
Spicetify v2.37.7
```

### 📝 Bug Description

I know full-screen mode is mainly for actual music, per https://github.com/daksh2k/Spicetify-stuff/issues/96#issuecomment-1656736883, but the currently playing podcast name is not displayed in full-screen mode. (TV or non)
Reproduce by having any podcast currently playing in full-screen mode.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/4bf77acd-5dcd-4581-ad4c-37bac933f502)

**Comment by daksh2k** [comment]
I can see only the name,
<img width="1027" alt="image" src="https://github.com/user-attachments/assets/ded05330-5d20-48c5-9e54-7ee30a2c0f10">
It doesn't show up as undefined for me, if there is no artist it is simply empty.
and if I enable the album setting, it shows the name
<img width="1168" alt="image" src="https://github.com/user-attachments/assets/a4e53cce-d2a4-49d8-8da7-b55108c9c4d5">
