### ISSUE TITLE
[Bug]: Play next extension not working

### ISSUE THREAD

**Issue by notmyung** [daksh2k/Spicetify-stuff#194]
### 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?

- [X] I have confirmed that I am using the latest versions.

### 🔍 Have you checked for an existing issue?

- [X] I have checked existing issues, both open and closed.

### 🔍 Have you reviewed pinned issues?

- [X] I have reviewed the pinned issues.

### Select the relevant extension for this bug report.

Play Next

### ℹ System Information

```Markdown
Spotify for Windows (64 bit)
1.2.47.364.gf06e5cee
Spicetify v2.38.3
Theme: Sleek / RosePine
Extensions: phraseToPlaylist.js, css-editor.js, shuffle+.js, skipStats.js, playNextWrapper.js, adblock.js
Custom apps: lyrics-plus, stats, marketplace
```

### 📝 Bug Description

Play next just doesn't show up anymore, ive tried uninstalling and resetting spicetify and reinstalling manually as well, and it still doesn't work.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/4fdfad18-7f9d-44ea-b061-83ba91034cb4)

**Comment by daksh2k** [comment]
Hi you may need to downgrade to a lower version, Spicetify is not supported for your version currently (1.2.47), extension won't work until support is added, all extensions using context menu are impacted.

https://docs.google.com/spreadsheets/d/1wztO1L4zvNykBRw7X4jxP8pvo11oQjT0O5DvZ_-S4Ok/edit?gid=803394557#gid=803394557
