### ISSUE TITLE
[Feature Request]: Playback Speed Control Extension

### ISSUE THREAD

**Issue by cleanerspam** [daksh2k/Spicetify-stuff#199]
### Choose the extension for feature request.

🎆 New Extension Idea

### 📝 Provide a description of the new feature

A playback speed increment extension that would allow changing playback speed from 0.5x to 2x with incrment of 0.1 by a slider like the volume slider 

### ➕ Additional Information

It should remember previous playback speed between different sessions and if possible between playlists

**Comment by daksh2k** [comment]
Not technically possible.
