### ISSUE TITLE
[Feature Request]: Use Artist fullscreen picture on fullscreen mode

### ISSUE THREAD

**Issue by rafajrichard** [daksh2k/Spicetify-stuff#20]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

When using fullscreen mode the extension allows using only a solid color or a blurred artwork. I would like to also use the Artist picture as used in TV mode since I much prefer the layout of the fullscreen mode (bigger artwork) but really like the artist background.

**Comment by daksh2k** [comment]
Added in `v2.0.0`.
