### ISSUE TITLE
[Bug]: Screen blanks when audio player refreshes

### ISSUE THREAD

**Issue by PasttaTypo** [daksh2k/Spicetify-stuff#203]
### 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?

- [X] I have confirmed that I am using the latest versions.

### 🔍 Have you checked for an existing issue?

- [X] I have checked existing issues, both open and closed.

### 🔍 Have you reviewed pinned issues?

- [X] I have reviewed the pinned issues.

### Select the relevant extension for this bug report.

Full Screen Mode

### ℹ System Information

```Markdown
Spotify for Windows (64 bit)
1.2.45.454.gc16ec9f6
Spicetify v2.38.4
xpui_2024-08-26_1724674643080_c16ec9f
cef_127.3.4+ge9e2e14+chromium-127.0.6533.100
Runtime: Chrome
Build System: Bazel
Extensions: Full Screen Display, Quick Queue, Sleep Timer Updated, adblockify, Seek Song Keybinds, Power bar
Apps: Enhancify
```

### 📝 Bug Description

Playing a song/album directly from an artist page or search results blanks the screen if Spotify hasn't been refreshed in a few minutes. (Force Reload briefly fixes it) Doesn't happen when I disable FSD or when playing a song from my playlists.

### 📸 Screenshots

https://github.com/user-attachments/assets/424a69ae-f93f-4f3d-94c3-22b1ffaca5a4

**Comment by daksh2k** [comment]
Can't reproduce the issue, extension doesn't change anything if it's not activated, so I doubt full screen is causing this issue.
Also update your Spotify, seems pretty old.
