### ISSUE TITLE
[Bug]: Can't Play Next an album

### ISSUE THREAD

**Issue by megatron008** [daksh2k/Spicetify-stuff#204]
### 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?

- [X] I have confirmed that I am using the latest versions.

### 🔍 Have you checked for an existing issue?

- [X] I have checked existing issues, both open and closed.

### 🔍 Have you reviewed pinned issues?

- [X] I have reviewed the pinned issues.

### Select the relevant extension for this bug report.

Play Next

### ℹ System Information

```Markdown
Spotify for Windows 1.2.51.345.gcc39d911
Spicetify V2.38.4
Extensions: playNextwrapper.js, savePlaylistWrapper.js,volumePercentageWrapper.js, hidePodcasts.js, cacheCleaner.js, QueueTime.js
Custom Apps: marketplace, lyrics-plus
```

### 📝 Bug Description

As detailed on the title, before we could Play Next any album, but we can't anymore. Im reporting from both latest versions on Windows PC but, it's been happening for at least 2 months now. 

### 📸 Screenshots

![Screenshot_2](https://github.com/user-attachments/assets/fd18d282-2f59-47db-8753-a38e338d16f7)

**Comment by daksh2k** [comment]
Should be fixed now @megatron008 
Thanks for raising the issue!

**Comment by megatron008** [comment]
> Should be fixed now @megatron008 Thanks for raising the issue!

Yes it is fixed! I just checked. Thank you for your amazing extension!
