### ISSUE TITLE
[Feature Request]: suggestion

### ISSUE THREAD

**Issue by Maguz0** [daksh2k/Spicetify-stuff#206]
### Choose the extension for feature request.

🎆 New Extension Idea

### 📝 Provide a description of the new feature

Could you make or add some configuration that makes the lyrics of the song take the color of the icons and volume, playing bar, I hope it is understood

### ➕ Additional Information

![Spotify premium 3 dic  2024 7_12_12](https://github.com/user-attachments/assets/b2fbb5c2-f0fe-44ad-8832-75b4be196c55)
In the screenshot you can see the white letter and if you could get the color of the icons (purple) in that case it would look nicer thanks

**Comment by daksh2k** [comment]
It's by design, text has to be readable everywhere, even if it's a picture background.
