### ISSUE TITLE
[Bug]: Lyrics animation choppy

### ISSUE THREAD

**Issue by justhereforjava** [daksh2k/Spicetify-stuff#207]
### 🔍 Have you ensured you are using the latest versions of Spotify, Spicetify, and the extension?

- [X] I have confirmed that I am using the latest versions.

### 🔍 Have you checked for an existing issue?

- [X] I have checked existing issues, both open and closed.

### 🔍 Have you reviewed pinned issues?

- [X] I have reviewed the pinned issues.

### Select the relevant extension for this bug report.

Save Playlists

### ℹ System Information

```Markdown
Spotify for Windows (64 bit)
1.2.52.442.g01893f92
Spicetify v2.38.5
Theme: marketplace
Extensions: adblock.js, romaji_lyrics.js, romaja_lyrics.js, beautiful-lyrics.mjs, fullScreenWrapper.js
Custom apps: lyrics-plus, marketplace
```

### 📝 Bug Description

lyrics have little to no scrolling animation, it worked previously

### 📸 Screenshots

https://youtu.be/8KX37KCoMn8

**Comment by sourya2007** [comment]
facing same problem also the lyrics on/off button has disappeared

**Comment by daksh2k** [comment]
Should be fixed now, thanks for reporting this !

**Comment by daksh2k** [comment]
@sourya2007 yes it's been replaced with the queue button, if you still need to toggle lyrics, you can use the keyboard shortcut `L`.
