### ISSUE TITLE
Full Screen Mode not working

### ISSUE THREAD

**Issue by Akshit-Senpai** [daksh2k/Spicetify-stuff#23]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.94.870.gf994cb0b
- Spicetify version: 2.13.1
```

### 📝 Description

Unable to start full screen mode on Spotify.
As you can see I have the extension installed but not button is showing up.
Also, nothing happens on pressing 'T' or 'F'.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/76200198/190556962-7a87510f-3afc-4352-96d9-f0196bd13c2c.png)

**Comment by daksh2k** [comment]
Should be fixed now, may take a little while to update, thanks for letting me know.
