### ISSUE TITLE
[Bug]: popup lyrics not working

### ISSUE THREAD

**Issue by Tetrax-10** [daksh2k/Spicetify-stuff#24]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Other

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 96
- Spicetify version: 2.14.0
```

### 📝 Description

Some songs dont have lyrics, but i can see the lyrics in spotify and lyrics plus.
Some its just red not working

### 📸 Screenshots

Some songs dont have lyrics, but i can see the lyrics in spotify and lyrics plus.
![image](https://user-images.githubusercontent.com/75513645/196221211-3860b40f-b180-462f-965c-c14042bd14c4.png)

Some its just red not working
![image](https://user-images.githubusercontent.com/75513645/196221267-91af7ef6-2fa6-4fed-ac7c-f981fe8cd464.png)

**Comment by daksh2k** [comment]
Actually it's not really my extension it's on the main [repo.](https://github.com/spicetify/spicetify-cli/blob/master/Extensions/popupLyrics.js). The extension in this repo is not really that different from original just some extra config options for personal use.
You can open a new issue on the main repo regarding this.
Also see [this](https://github.com/spicetify/spicetify-cli/issues/1827) seems to be the same issue.
