### ISSUE TITLE
[Bug]:  Full screen mode lyrics

### ISSUE THREAD

**Issue by FireTxpsy** [daksh2k/Spicetify-stuff#26]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows 1.1.97.962.g24733a46
- Spicetify version: 2.14.1
```

### 📝 Description

No matter what, i can not show the song lyrics in the full screen mode

### 📸 Screenshots

![Screenshot 2022-10-29 220409](https://user-images.githubusercontent.com/116977537/198850606-81febda7-c5c7-487a-8928-a241ce714aa3.png)
![Screenshot 2022-10-29 220341](https://user-images.githubusercontent.com/116977537/198850613-5b0d1727-b839-4bb3-8d37-cd467fca36e7.png)

**Comment by eitan07** [comment]
i have the same issue :(

**Comment by eitan07** [comment]
Install lyrics plus
`spicetify config custom_apps lyrics-plus`
