### ISSUE TITLE
[Bug]: Lyrics don't show up

### ISSUE THREAD

**Issue by faketucker** [daksh2k/Spicetify-stuff#27]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.97.962.g24733a46
- Spicetify version: 0.8.2
```

### 📝 Description

I opened full-screen mode, but the lyrics don't show up. I have made sure that the song has the lyrics.
Extension is up to date from the latest spicetify marketplace.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/28383557/200105225-fde204be-d141-4c56-81ab-c69ffd13981a.png)

**Comment by faketucker** [comment]
Here are all the extensions installed.
![image](https://user-images.githubusercontent.com/28383557/200105724-8726dedc-6e2d-40a6-aad0-681f5b9b86cb.png)

I'm using Comfy theme.

**Comment by SIMULATAN** [comment]
You need the Lyrics+ Extension

**Comment by faketucker** [comment]
> You need the Lyrics+ Extension

Solved. Thank you.

**Comment by strat-ileris** [comment]
> You need the Lyrics+ Extension

I can't find the Lyrics+ Extension
