### ISSUE TITLE
How to change fullScreen.js background to album art instead of artist image?

### ISSUE THREAD

**Issue by devanramji** [daksh2k/Spicetify-stuff#3]
title.

I see this is a tweaked version off fullAppDisplay.js and on that one there was a setting that allowed me to choose an artist photo as the background screen or an enlarged and blurred album art image as the background. How can i switch this? thanks and sorry fi this isn't the right place to make this request.

**Comment by daksh2k** [comment]
There should be 2 buttons added for the extension, one in the top bar which has a tv icon and it activates the mode with artist background,
The other in the bottom right, next to the volume bar, the mode with the blur album background.

Tip- you can change multiple settings by right clicking anywhere which opens the config.

**Comment by daksh2k** [comment]
@devanramji  did that answer your question?
If so I'll be closing this issue.

**Comment by devanramji** [comment]
All good, thanks for your help!
