### ISSUE TITLE
[Bug]: Lyrics dont scroll to the top when song is repeated

### ISSUE THREAD

**Issue by Crucial-hash** [daksh2k/Spicetify-stuff#34]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.99.878.g1e4ccc6e
- Spicetify version: v2.14.3
```

### 📝 Description

When I am playing a song on repeat with non-compact lyrics and the song finishes, the lyrics don't scroll back up to the top of the page unlike the regular lyrics page.,

**Comment by daksh2k** [comment]
Does it also happen with the default `fullAppDisplay.js` extension that comes bundled with Spicetify?

I'll investigate it a bit, but I think a fix will probably be needed in `lyrics-plus` rather than this extension. I'll see if there is a workaround.

**Comment by Crucial-hash** [comment]
Yes, I have tried it with both and it just does not scroll back to the top.

**Comment by daksh2k** [comment]
I am closing the issue currently, as this is not an extension issue, but a `lyrics-plus` issue, Feel free to open an issue with details on the main lyrics-plus repo [here](https://github.com/spicetify/spicetify-cli)
