### ISSUE TITLE
[Feature Request]: add lyrics translation support

### ISSUE THREAD

**Issue by niruvibes** [daksh2k/Spicetify-stuff#35]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Allow language conversion extensions to work on your full app display mod
examples: Japanese Romaji Lyrics, Korean Romaji Lyrics

### ➕ Additional Information

I don't have a proposed solution as it uses lyrics+ app to function and the extensions only affect the normal lyrics menu, maybe an option to pull lyrics off that

**Comment by daksh2k** [comment]
Hey @niruvibes, isn't this added in `lyrics-plus` currently, so I think I can close this issue. 
Feel free to reopen if you mean something else.

**Comment by niruvibes** [comment]
Hey @daksh2k this is on lyrics + but the translations dont seem to sync over to this, i assumed it was the way the lyrics were being fetched on this app so i opened an issue. Not a big deal, feel free to not bother as people probably dont care about this

**Comment by daksh2k** [comment]
It's working fine for me, maybe you are using an older `lyrics-plus`? @niruvibes
This functionality is now integrated with `lyrics-plus` so you don't need a separate extension for that.

<img width="1792" alt="Screenshot 2023-03-07 at 5 25 41 PM" src="https://user-images.githubusercontent.com/42179185/223415202-2579fef3-0673-4ba4-a71d-9dbeb04b0c44.png">
