### ISSUE TITLE
[Bug]: Lyrics not visible for songs

### ISSUE THREAD

**Issue by BeastCodZ** [daksh2k/Spicetify-stuff#36]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.0.1165.gabf054ab
- Spicetify version: v2.14.3
```

### 📝 Description

Any song lyrics not visible in full screen mode

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/62057520/207237741-5befae83-7b9e-44ef-aa62-d2bd1071b56f.png)

**Comment by SIMULATAN** [comment]
Install the Lyrics+ Extension

**Comment by BeastCodZ** [comment]
![image](https://user-images.githubusercontent.com/62057520/207272098-9a5cebd8-2f51-4d64-a13b-baff9b002961.png)
Invalid Lyrics for some songs
Is it not possible to add the lyrics which are given by spotify itself
![image](https://user-images.githubusercontent.com/62057520/207272204-a45fe3da-d3f7-4fcf-a4d3-ff3928f264de.png)
these lyrics are valid

**Comment by daksh2k** [comment]
You can customize the `lyrics-plus` settings from the profile menu when in the `lyrics-plus` custom app.
Change the providers, colors, and fonts in that to your preference.

More info [here](https://github.com/spicetify/spicetify-cli/tree/master/CustomApps/lyrics-plus)
