### ISSUE TITLE
[Feature Request]: Integration with star ratings addon

### ISSUE THREAD

**Issue by CodedNil** [daksh2k/Spicetify-stuff#37]
### Choose the extension for feature request.

🎆 New Extension Idea

### 📝 Provide a description of the new feature

Not sure the feasibility of this since it is another extension, but it would be really neat if similar to how there is a like song button, you could have the 5 buttons to choose a songs star rating if that extension is installed, that way I could leave the plugin in fullscreen mode most of the time.

**Comment by daksh2k** [comment]
I am closing the issue currently, as this is currently not in the scope of this extension, and will require main work from the star rating's author side.

I think this feature request will be more suitable for [Star Ratings](https://github.com/duffey/spicetify-star-ratings)  to introduce, but I'll be happy to collaborate with @duffey for any changes required on the UI side for easier integration if he plans to support it.
