### ISSUE TITLE
[Bug]: It is not showing the fullscreen icon in the bottom right any more.

### ISSUE THREAD

**Issue by AstroSB** [daksh2k/Spicetify-stuff#38]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
Spotify for Windows
1.2.0.1165.gabf054ab
It says in Spotify Info Spicetify version: v2.14.3
But in in the shell it says Spicetify version: 2.16.0
```

### 📝 Description

Soooo i downloaded the extension and i really liked it it looked so cool and fancy now the button to access the custom fullscreen just vanished and is nowhere to be seen.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/107926972/210851482-4f2d84f4-9e66-4a33-b0e2-3740e7c6a514.png)
![image](https://user-images.githubusercontent.com/107926972/210851525-86f00b34-1648-4481-af09-4d829b81cf4e.png)

**Comment by daksh2k** [comment]
Hi, can you share any errors you see in console logs from this extension?

To see first enable by running `spicetify enable-devtools`, then `ctrl+shift+i` inside spotify to open.

**Comment by AstroSB** [comment]
![image](https://user-images.githubusercontent.com/107926972/211100166-99ec3f5c-0213-48ea-8670-a365833085be.png)
Yes a lot

**Comment by AstroSB** [comment]
![image](https://user-images.githubusercontent.com/107926972/211100268-8d05a061-d728-4386-86b0-dd113e2a08fd.png)
I guess that´s it

**Comment by daksh2k** [comment]
Can you try now? @AstroSB  
I updated the URLs in https://github.com/daksh2k/Spicetify-stuff/commit/782acf3b8cc6d69f467b315d2eb8a1e588b75ccb, if the issue still persists reopen this issue :)
