### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by bog4t** [daksh2k/Spicetify-stuff#39]
### Choose the extension for feature request.

Auto Skip

### 📝 Provide a description of the new feature

Skip liked songs, this would be very helpful for finding new songs I've yet to discover.

**Comment by daksh2k** [comment]
Added in https://github.com/daksh2k/Spicetify-stuff/commit/7791d01025e4b90c877fc0d15f51c83eef1e72d4 .
