### ISSUE TITLE
[Bug]: Lyrics are not shown in full screen mode

### ISSUE THREAD

**Issue by itsmehrdadz** [daksh2k/Spicetify-stuff#40]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 
- Spicetify version: 
Spotify for Windows
1.2.0.1165.gabf054ab
Spicetify v2.16.0
```

### 📝 Description

Hi there, This feature on spicetify is amazing. But it has an issue that on full-screen mode, lyrics are not shown.

### 📸 Screenshots

![Screenshot 2023-01-12 120328](https://user-images.githubusercontent.com/97160081/212487204-733f9d73-a5cf-4c54-bdad-5529acf5167c.png)
![Screenshot 2023-01-12 120349](https://user-images.githubusercontent.com/97160081/212487220-2ce5ef34-0c6f-40a5-b465-c7eb134e1a42.png)

**Comment by SIMULATAN** [comment]
Install the lyrics+ extension

**Comment by itsmehrdadz** [comment]
where is that?

**Comment by daksh2k** [comment]
Follow this [note?](https://github.com/daksh2k/Spicetify-stuff/blob/master/EXTENSIONS.md#note-you-need-lyrics-plus-custom-app-for-showing-lyrics-in-the-extension) @itsmehrdadz
