### ISSUE TITLE
[Bug]: No lyrics are showing up in full screen mode

### ISSUE THREAD

**Issue by R3tr003** [daksh2k/Spicetify-stuff#41]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for macOS (Apple Silicon)
1.2.3.1115.gd61a8f5c
- Spicetify version: v2.16.0
```

### 📝 Description

Hi I have the same problem as the last bug I saw recently I tried all the solutions on my Mac, but the custom-app is not working because it is not displayed in the folder after the execution on the terminal. if there is any solution thanks.

### 📸 Screenshots

<img width="1440" alt="Screenshot 2023-01-23 at 02 29 51" src="https://user-images.githubusercontent.com/26939969/213952254-f6147829-e9a4-4516-9ed4-491c5a14fbb3.png">
<img width="1440" alt="Screenshot 2023-01-23 at 02 31 14" src="https://user-images.githubusercontent.com/26939969/213952349-a5f29f01-ba00-4815-b127-3a833a0f5105.png">

**Comment by daksh2k** [comment]
Check pinned issue

**Comment by daksh2k** [comment]
Can you share your home screen, and terminal output on what you get after executing, also share this modal by going to 
Spotify -> About Spotify
<img width="625" alt="Screenshot 2023-01-23 at 3 22 02 PM" src="https://user-images.githubusercontent.com/42179185/214010409-70ca13b5-2ad7-40b3-af7b-95e3c76b59d7.png">

**Comment by mv-fs** [comment]
I get the same bug on Win10, Spicetify v2.16.0 and in the modal info I get :

> Spotify for Windows
> 1.2.3.1115.gd61a8f5c
> Spicetify v2.16.0
> Theme: Dribbblish / gruvbox
> Extensions: songstats.js, wikify.js, hidePodcasts.js, skipStats.js, listPlaylistsWithSong.js, spotifyBackup.js, playEnhancedSongs.js, featureshuffle.js, fullScreenWrapper.js, skipOrPlayLikedSongs.js, genre.js, goToSong.js, playNextWrapper.js, copytoclipboard2.js, dribbblish.js
> Custom apps: marketplace

Here's my home screen 
![image](https://user-images.githubusercontent.com/49976617/214959913-040d5a8b-343d-4b56-af4c-855da4e88465.png)


Not entierly sure what terminal output you are expecting, if I restart using powershell I just get `spicetify v2.16.0`

**Comment by daksh2k** [comment]
@mv-fs @R3tr003 

Install lyrics plus
`spicetify config custom_apps lyrics-plus`
Then apply the changes
`spicetify apply`
