### ISSUE TITLE
[Feature Request]: Filter Option To Remove Stock Fullscreen Button

### ISSUE THREAD

**Issue by zero-mindset** [daksh2k/Spicetify-stuff#42]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Hi, I was wondering if it’d be possible to add an option to toggle off Spotify’s stock fullscreen button. As is, without using a theme, there are two fullscreen buttons which is a little awkward to look at. Not a massive deal, but that would make it perfect imo. I greatly appreciate this extension in general!

**Comment by daksh2k** [comment]
Added in `v2.0.0`.

**Comment by zero-mindset** [comment]
All the changes look great. I appreciate it!
