### ISSUE TITLE
[Bug]: Doesn't show the lyrics and can't change the time of the song

### ISSUE THREAD

**Issue by OrginalSh4dow** [daksh2k/Spicetify-stuff#45]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for windows 1.2.3.1115.gd61a8f5c
- Spicetify version: v2.16.1
```

### 📝 Description

I have the fullscreen extension installed and if I go into full screen I can't see the lyrics and I can't skip to a certain point of the song.
I hope it can be fixed

### 📸 Screenshots

Here is a example
![T I  - That's All She Wrote 2_2_2023 9_05_40 PM](https://user-images.githubusercontent.com/77278894/216438094-b6c1b8f5-e22e-4fd9-a1a0-423bde7e2e68.png)

**Comment by SIMULATAN** [comment]
To fix the lyric issue, see [this note](https://github.com/daksh2k/Spicetify-stuff/blob/master/EXTENSIONS.md#note-you-need-lyrics-plus-custom-app-for-showing-lyrics-in-the-extension).
About the time of the song; I vaguely remember this being a limitation with spotify, but since I'm not certain, we'll have to wait what @daksh2k says.

**Comment by daksh2k** [comment]
1. Currently the seek bar is not interactable, so you can't seek using that but keyboard shortcuts work, that will come in a future update. 

2. For lyrics you need the `lyrics-plus` custom app, which you can get by following the steps mentioned in the previous comment.

**Comment by daksh2k** [comment]
Added in `v2.0.0`.
