### ISSUE TITLE
[Feature Request]: show a lyrics+ notice

### ISSUE THREAD

**Issue by SIMULATAN** [daksh2k/Spicetify-stuff#46]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

There are PLENTY of people coming here regularly to report that lyrics don't work.
However, there already is [a note](https://github.com/daksh2k/Spicetify-stuff/blob/master/EXTENSIONS.md#note-you-need-lyrics-plus-custom-app-for-showing-lyrics-in-the-extension) explaining how to fix it.
Unfortunately, many people seem to miss it.

### ➕ Additional Information

I propose to add a little text along the lines of "To display lyrics; install lyrics+" where the lyrics would usually go on the first start.
An alternative would be to add the notice to the settings menu or to make it show every time until it's manually turned off.
Or maybe, the best idea would be to add the message with an acknowledge button.

I believe that many people seem to miss it because they either just read the project's README but not the EXTENSIONS.md file, or because they install them through the spicetify marketplace, which doesn't show the EXTENSIONS file either.

**Comment by daksh2k** [comment]
I know right, it's so annoying lol, I want to pin it at the top of the readme in bold haha but I added this in the settings section for the next update of the extension.

<img width="574" alt="Screenshot 2023-02-03 at 2 22 43 PM" src="https://user-images.githubusercontent.com/42179185/216555015-b0a376ac-f83a-485e-858a-fd9903043e88.png">

**Comment by daksh2k** [comment]
Added in `v2.0.0`.
