### ISSUE TITLE
[Feature Request]: option to disable the official fullscreen button 

### ISSUE THREAD

**Issue by Yashirow** [daksh2k/Spicetify-stuff#47]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

I've read in [this issue](https://github.com/daksh2k/Spicetify-stuff/issues/17) that you added your icon without removing the official one but could it be possible to add an option to disable the official one ? Thanks.

**Comment by Yashirow** [comment]
I created a custom snippet with this CSS line and it's working.  `button[title="Full screen"] { display: none !important; }`
I'm closing the issue.

**Comment by daksh2k** [comment]
Added in `v2.0.0`.
