### ISSUE TITLE
[Bug]: Album name on TV mode is misaligned when icons are disabled

### ISSUE THREAD

**Issue by Yashirow** [daksh2k/Spicetify-stuff#49]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863
- Spicetify version: 2.16.2
```

### 📝 Description

When icons are disabled in the settings the album name on TV mode is misaligned. Screenshots below.

### 📸 Screenshots

With icons :
![image](https://user-images.githubusercontent.com/100087778/222791328-2f82c6e0-c5f1-4be7-bbc9-4e962e17204b.png)

Without icons :
![image](https://user-images.githubusercontent.com/100087778/222791432-dfeb4b40-93f7-4474-8975-2f6f4fd11a7d.png)

**Comment by daksh2k** [comment]
Fixed in `2.0.1`
