### ISSUE TITLE
[Bug]: Progress bar not centered

### ISSUE THREAD

**Issue by Yashirow** [daksh2k/Spicetify-stuff#50]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.6.863
- Spicetify version: 2.16.2
```

### 📝 Description

Figured out that the new progress bar is not correctly centered.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/100087778/222794698-3000b66c-11e2-492f-aa65-5e984a5ebb68.png)

**Comment by daksh2k** [comment]
Wow, that was an acute observation, hopefully it's fixed now.

**Comment by Yashirow** [comment]
Yes it's fixed, thanks !
