### ISSUE TITLE
[Feature Request]: option to resize album art for full screen mode

### ISSUE THREAD

**Issue by catalpaaa** [daksh2k/Spicetify-stuff#52]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Makes the album art resizeable so it looks good on narrow window szie.

### ➕ Additional Information

![image](https://user-images.githubusercontent.com/89681913/222878062-6a03345b-378f-4bbe-9f70-bb576b174e49.png)
This is how it shows stuff when the window is not wide enough

**Comment by daksh2k** [comment]
@catalpaaa  This should be solved in v`2.1.0`. I added responsive styles, this means that the album art will get smaller when there is not much space. Let me know if this doesn't solve the issue.
