### ISSUE TITLE
[Feature Request]: Ken Burns Effect

### ISSUE THREAD

**Issue by Damienlee69** [daksh2k/Spicetify-stuff#57]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

I just thought it would be nice (if possible) to have the Ken Burns effect on the background image. Found another git that is working with it, if nothing but for examples of it.

https://github.com/changbowen/Ken-Burns-Slideshow

**Comment by daksh2k** [comment]
Hi @Damienlee69, this sounds like a good idea, I tried it but had these concerns
1. A single image for a whole song will either be too slow, or the effect will get over in the first couple of seconds, so it's the same static image.
2. Also it's challenging to set a generalized pattern where to focus/zoom in on the image, as it will depend on the song and bg itself.
