### ISSUE TITLE
[Feature Request]: More configuration options to manage components

### ISSUE THREAD

**Issue by insanowsky** [daksh2k/Spicetify-stuff#59]
### Choose the extension for feature request.

🎆 New Extension Idea

### 📝 Provide a description of the new feature

+ progress bar ON HOVER/MOUSE MOVEMENT
+ player controls ON HOVER/MOUSE MOVEMENT
+ customize lyrics position as as movable box or just let us customize alignment
+ player control colors customisation

**Comment by daksh2k** [comment]
Added in `v2.5.0`, lyrics alignment can already be customized.

**Comment by nelecpg** [comment]
> Added in `v2.5.0`, lyrics alignment can already be customized.

i think what @insanowsky was talking about having the ability to move the field lyrics-plus is contained in closer/further towards the album art/controls components. as of now, there seems to be a substantial amount of space between the two parts.
![image](https://github.com/daksh2k/Spicetify-stuff/assets/171105839/9556e05b-f0c4-4a5e-ae35-76e38f39102a)
an option to move these two closer could make it more appealing for left alignments seen above.
