### ISSUE TITLE
Functional seek bar? (enhancement)

### ISSUE THREAD

**Issue by SupLiCatinG** [daksh2k/Spicetify-stuff#6]
A functional seek bar for fullscreen.

![image](https://user-images.githubusercontent.com/94017480/152345484-4c88587c-5178-4599-92c4-5e8724fbe283.png)

**Comment by zxsilenx** [comment]
Yeah, working fullscreen volume bar would be very cool.

**Comment by daksh2k** [comment]
Added in `v2.0.0`. @SupLiCatinG . Finally 😂
