### ISSUE TITLE
[Feature Request]: Option To Play Podcast/Song Video When Available

### ISSUE THREAD

**Issue by Crucial-hash** [daksh2k/Spicetify-stuff#62]
This is a great extension that I have been using on a small display below my monitors, I think it would be great to make an option where you can view the video of a song or podcast (maybe add an option where it only plays the video if it is a podcast or a song) automatically when a podcast or song is played that has a video available in fullscreen.

I think there may be a better way of implementing this but a few toggles in the settings I feel would be plenty.

Please consider this!

**Comment by daksh2k** [comment]
That would be like creating a whole youtube player inside the extension, it can be done but I don't think it will look as good as Youtube Music! There will be no point in showing album art and lyrics on a video, so it would be just a video player, or If the video occupies only a small portion then it wouldn't make any sense.
This will be out of the scope of this extension, feel free to add a comment if you meant something else, I am closing the issue currently.
