### ISSUE TITLE
[Feature Request]: Add to playlist.

### ISSUE THREAD

**Issue by dfk789** [daksh2k/Spicetify-stuff#63]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Hi, I would appreciate it very much if you could add the ability to add the current song to a playlist(s).

**Comment by dfk789** [comment]
I wanted this enough that I have started working on it myself.  I almost have it ready enough for my own usage, just need to have it show folders as well. 
![image](https://github.com/daksh2k/Spicetify-stuff/assets/597765/28a62360-e7b2-4e9e-8e51-31bda6bc0059)

**Comment by daksh2k** [comment]
Hey @dfk789 nice work for integrating, but I was thinking rather just add playlist functionality we can use the whole context menu provided by spotify itself see #67 for more information, so this feature will automatically be solved.

That context menu is a little tricky to implement, but I am looking into it.

So closing this issue.
