### ISSUE TITLE
[Bug]: Spotify muted after auto-skipping songs.

### ISSUE THREAD

**Issue by bog4t** [daksh2k/Spicetify-stuff#64]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Auto Skip

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.10.760.g52970952
- Spicetify version: 2.17.2
```

### 📝 Description

Steps:
1. Clear queue.
2. Play any song and pause it.
3.  Set auto-skip to liked songs.
4. Enqueue 2-5 liked songs and 1 unliked song.
5. Press play and skip to next song.

Expected behavior: Will play unliked song without any changes to the volume.
What happens: Volume is muted once the queue reaches the unliked song after skipping.

**Comment by daksh2k** [comment]
Yeah, I am sometimes able to reproduce it, it's very flaky, sometimes it happens for a large number of skips together, otherwise primarily for 1-2 songs it does not. 

I was thinking of removing the mute functionality altogether, I don't know if that's useful. Any thoughts?

**Comment by bog4t** [comment]
Personally, I don't think it's very useful. I don't mind the small blips of audio that may come up while it skips.

**Comment by daksh2k** [comment]
Should be fixed now, mute functionality will only function when doing some callback i.e. say when you play a remix song and you have auto skip set to skip remix songs, the extension tries to find the non-remix version of that song and replaces that in your queue.

**Comment by bog4t** [comment]
Awesome, everything seems to work fine on my end.
