### ISSUE TITLE
[Feature Request]: Option to disable rounded album art corners

### ISSUE THREAD

**Issue by bjia1999** [daksh2k/Spicetify-stuff#68]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Small thing but would be nice to be able to view the entire album artwork.

**Comment by SIMULATAN** [comment]
I'm a bit confused right now, it's rectangular for me and always has been in the months using the extension.
![image](https://user-images.githubusercontent.com/63104422/235686864-7435071f-9166-4ba0-ba05-306ed283adfe.png)

**Comment by daksh2k** [comment]
@bjia1999 Closing this as invalid, I think this is because you have a theme or extension installed which is conflicting with this.

**Comment by bjia1999** [comment]
Sorry forgot to respond to this a couple of weeks ago. I was referring to the slightly rounded corners on the album art in full screen as opposed to the sharp corners in the normal view. 

![image](https://github.com/daksh2k/Spicetify-stuff/assets/16867185/f29082c8-1255-46f2-995e-47224a90021a)

![image](https://github.com/daksh2k/Spicetify-stuff/assets/16867185/dd991cb6-7ab3-4728-9724-3099adb3b2af)

Like I said really small thing but I would like to be able to see the entire album art in full screen.
