### ISSUE TITLE
[Feature Request]: animated album artwork

### ISSUE THREAD

**Issue by TrulyyGold** [daksh2k/Spicetify-stuff#69]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Animated album artwork, nothing much to say xD

![image](https://github.com/daksh2k/Spicetify-stuff/assets/113952990/495ecd8d-6d8d-4b29-8643-5a31017283b4)

**Comment by Goldingotzzz** [comment]
also issue #69 lol

**Comment by daksh2k** [comment]
Animated in the sense, song change animation is already there?

**Comment by Goldingotzzz** [comment]
the album artwork, an example for yeat's album artwork:
https://tenor.com/view/yeat-afterlyfe-album-split-twizzy-gif-27656986

**Comment by daksh2k** [comment]
Okay, I don't think Spotify shows animated artwork anywhere, getting artwork for a song from outside, may be a little tricky.
Where did you get the gifs from? I'll see if it's feasible and good enough, otherwise, this might be out of scope.

**Comment by TrulyyGold** [comment]
Sorry for slow response, this is actually an Apple Music feature!

**Comment by daksh2k** [comment]
Oh, no worries, I looked into it, there is no publically available data for animated artworks that can be reliably used here. As far as I know, only Apple Music does this stuff. 

Even if I were able to fetch that data from apple music there is a restriction on mp4 videos in Spotify, you can't play them inside Spotify. So currently this will be out of scope, feel free to add a comment here if you want to include some more information. I am closing the issue currently.

**Comment by TrulyyGold** [comment]
> Okay, I don't think Spotify shows animated artwork anywhere, getting artwork for a song from outside, may be a little tricky. Where did you get the gifs from? I'll see if it's feasible and good enough, otherwise, this might be out of scope.

I found out Spotify Premium has this feature the same way Apple Music 🤑
