### ISSUE TITLE
Lyrics?

### ISSUE THREAD

**Issue by AdnanZXgamer** [daksh2k/Spicetify-stuff#7]
for some reason the lyrics arent showing up for me in fullscreen or in TV mode
![image_2022-02-13_012904](https://user-images.githubusercontent.com/92264668/153732101-459ba903-bac4-45d2-afce-801669421dd7.png)

**Comment by daksh2k** [comment]
You need the `lyrics-plus` custom app for that.
It comes bundled with [Spicetify](https://spicetify.app/docs/getting-started/custom-apps), just run 
```
spicetify config custom_apps lyrics-plus
spicetify apply
```

**Comment by AdnanZXgamer** [comment]
Alright! thank you so much!
