### ISSUE TITLE
[Bug]: Animated background lower frames

### ISSUE THREAD

**Issue by plopin3472** [daksh2k/Spicetify-stuff#74]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Spicetify version: 2.17.2
```

### 📝 Description

Animated background plays slowly when hardware acceleration is disabled AND after Spotify is executed, but does the opposite when executing it while acceleration is enabled. Should be fixed by just disabling it as Spotify runs/ after enabled, so to save a few resources.

**Comment by plopin3472** [comment]
Heavy themes seem to worsen this.

**Comment by daksh2k** [comment]
Yeah, the option is experimental and resource intensive, that's why there is a warning, 
not sure what you mean by after Spotify is executed. Can you elaborate more?
Disabling Hardware acceleration will of course slow down the animation because GPU will be disabled, so don't disable that.

**Comment by plopin3472** [comment]
> not sure what you mean by after Spotify is executed. Can you elaborate more?

When you open it, after doing those acceleration changes & closing.

**Comment by daksh2k** [comment]
Hi, there is a new setting in `v2.3.0` to modify animation speed. Still, due to the nature of animation and its implementation, the frames will be lower when you disable hardware acceleration, as it won't get enough resources to animate.
