### ISSUE TITLE
[Bug]: Full Screen Mode Lyrics Gap

### ISSUE THREAD

**Issue by surya27895** [daksh2k/Spicetify-stuff#75]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.11.916.geb595a67
- Spicetify version: v2.18.1
```

### 📝 Description

Its looks like more gap than before in new update, hope there any workaround for that or option to change the lyrics width

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/22859567/da8ca9b1-b912-465e-a75e-0128dcd9f025)

**Comment by daksh2k** [comment]
should be fixed in `v2.2.1`
