### ISSUE TITLE
[Feature Request]: Lyrics Font Size Control

### ISSUE THREAD

**Issue by InsanityPrelude** [daksh2k/Spicetify-stuff#76]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Hi there!  I use Full Screen Mode quite a bit, and recently I've switched to using vertical side monitors.  This works out great for workflow, and when I'm not using one of my monitors I can easily put Spotify up on it.

The problem is that at 9:16 Full Portrait aspect ratio, there's not much space at all for the lyrics.  This is more or less egregious depending on the song, but it frequently results in only being able to fit three or four words horizontally on the screen.  The title of this feature request is my suggested solution, just being able to reduce the font size to fit more words in the same space, but it'd probably also work to either reduce the margins between the album art and the words or to move the album art to the top and place the lyrics underneath.

I've included a picture below!
![image](https://github.com/daksh2k/Spicetify-stuff/assets/38642020/412f9717-85aa-49d7-9618-cfc3cbc3d25e)

**Comment by daksh2k** [comment]
You can already change the lyrics' font size from here

![image](https://github.com/daksh2k/Spicetify-stuff/assets/42179185/6bea19d7-6b28-4a78-b954-0cbf4f1a59b6)

**Comment by InsanityPrelude** [comment]
Oh, so it does... I've even been into that menu to adjust Track Delay, I just couldn't find it when I was actually looking for it the other day after the lyrics started to bother me.

Haha... well, I'm going to go crawl in a hole.  Thanks for the help!
