### ISSUE TITLE
[Feature Request]: slow down animated background or give option to change speed

### ISSUE THREAD

**Issue by Gamesnic** [daksh2k/Spicetify-stuff#80]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

The animated background looks really cool, but it looks a little too fast, almost as if it was fire. It would be better if there was an option to change the speed (probably preferably in percent between 5%-200%) so everyone could adjust it to their needs.

**Comment by daksh2k** [comment]
Added in `v2.3.0` 🙌
