### ISSUE TITLE
[Feature Request]: Animated Album Art is bad.

### ISSUE THREAD

**Issue by urthurao** [daksh2k/Spicetify-stuff#82]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

ngl, just really not a fan of it. its just a giant spinning album cover, and it it shows off the bottom right corner (my friends tab) of spotify while spinning. as a general concept, it looks pretty silly. 

i was expecting it to be some sort of automatically generated animated colour palette. one that matches the palette of the album artwork, or even just applying some swirly blend filters to the album art background would be cool.

**Comment by daksh2k** [comment]
You don't have to use the feature if you don't like it., it's experimental for a reason. :)
Next time maybe don't share feedback by being so rude and condescending.
