### ISSUE TITLE
[Bug]: fullscreen mode not showing lyrics

### ISSUE THREAD

**Issue by sashatoast** [daksh2k/Spicetify-stuff#85]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Spicetify version: 2.19
```

### 📝 Description

when i put spotify in fullscreen mode it doesn't show the song lyrics. I tried uninstalling other extension and snippets that modify the lyrics tab but it's still not working..

### 📸 Screenshots

![screenshot](https://github.com/daksh2k/Spicetify-stuff/assets/83813602/fb59b1e8-6219-48c5-b133-1e917ff6a4e3)

**Comment by SIMULATAN** [comment]
install lyrics+

**Comment by sashatoast** [comment]
already have it

**Comment by daksh2k** [comment]
You have to add lyrics-plus to the config, and then again run `spicetify apply`, it doesn't take automatically.

Check https://github.com/daksh2k/Spicetify-stuff/issues/26#issuecomment-1296229075 for steps.
