### ISSUE TITLE
[Feature Request]: Pause/slow down up next display speed 

### ISSUE THREAD

**Issue by thegoldknight** [daksh2k/Spicetify-stuff#86]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Hello, thanks for creating and maintaining this extension!
I have a small suggestion for the up next display on the full screen. 
The up next display scroll speed is quite fast and does not have a pause upon reaching the end. This is very apparent on medium length titles, as shown in the video. 

My proposal is to add a small pause upon reaching the end of the scroll, and then start to scroll back, similar to the way Spotify does it. 

### ➕ Additional Information
https://github.com/daksh2k/Spicetify-stuff/assets/135397968/4e1c8ba3-20c1-4d01-98ea-94e4c21a2c2e 

Have a good day,
Gold

**Comment by daksh2k** [comment]
Hi, I wrote the animation logic to be consistent for both short and long titles, felt it had the right speed, and will fine-tune it sometime later if I get time, but I think mostly it's fine. If I increase the stoppage time, on long titles the scrolling speed will increase a lot.  It's just a balance really. So closing this issue currently.
