### ISSUE TITLE
[Bug]: Toggle L for Lyrics not working in fullscreen

### ISSUE THREAD

**Issue by duckworx** [daksh2k/Spicetify-stuff#88]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Save Playlists

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.12.902.g1924b088
- Spicetify version: v2.20.0
```

### 📝 Description

While in fullscreen i tried to press `L` in hope it shows/unshows the lyrics. I'm using Nord theme by Tetrax if that is relevant

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/115400547/dffd4bfa-4f6f-4ad6-9597-d219a0081dac)

**Comment by daksh2k** [comment]
Should be fixed now @duckworx, was a bug only when extra controls were disabled. Thanks for reporting!
