### ISSUE TITLE
[Feature Request]: Show time on Full Screen

### ISSUE THREAD

**Issue by YoinkedYoink** [daksh2k/Spicetify-stuff#91]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Add an option to show the current time in TV and fullscreen mode.
Just a simple 24/12 hr clock with different alignment options such as center, top right, etc

### ➕ Additional Information

Example image of time in top right but obstructs the up next menu
![image](https://github.com/daksh2k/Spicetify-stuff/assets/87105685/01bf4c15-7c17-4901-891c-378f45724e03)

Example image of time in top left without obstructing anything
![image](https://github.com/daksh2k/Spicetify-stuff/assets/87105685/93df96bf-72c5-4a84-ae45-872caee3d14b)

**Comment by daksh2k** [comment]
It's not really a planned feature for now, as it wouldn't fit with the theme of the extension, and it might feel too cluttered. So closing this for now.
