### ISSUE TITLE
Unable to load marketplace

### ISSUE THREAD

**Issue by ANii693** [daksh2k/Spicetify-stuff#92]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Other

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows
1.2.13.661.ga588f749
Spicetify v2.20.1
```

### 📝 Description

I'm encountering an issue where the marketplace is not loading, the app themes and extensions are not functioning. I'm unable to identify the cause of the problem.

I have attached the ss how it  looks 

### 📸 Screenshots

![Screenshot (302)](https://github.com/daksh2k/Spicetify-stuff/assets/118979320/d1650157-a383-4226-95b5-cb6e66e36075)
![Screenshot (303)](https://github.com/daksh2k/Spicetify-stuff/assets/118979320/7b59d9ab-58c1-45b3-8027-15d2ba2e5798)
![Screenshot (304)](https://github.com/daksh2k/Spicetify-stuff/assets/118979320/0fde3136-572f-42df-833e-fe57fd7116aa)
![Screenshot (305)](https://github.com/daksh2k/Spicetify-stuff/assets/118979320/e6280d88-9e0f-435e-83ef-ec5ff84eddc6)

**Comment by SIMULATAN** [comment]
The Spicetify Marketplace is unrelated to daksh2k's Spicetify Extensions, it's developed by the official Spicetify team over at [spicetify/spicetify-marketplace](https://github.com/spicetify/spicetify-marketplace). Please open an issue there.

**Comment by ANii693** [comment]
ohk my bad
