### ISSUE TITLE
[Feature Request]: Background for Full Screen extension

### ISSUE THREAD

**Issue by adambnmohd** [daksh2k/Spicetify-stuff#94]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Can you add a background like this
https://github.com/surfbryce/beautiful-lyrics/blob/main/previews/fullscreen-preview.gif

**Comment by SIMULATAN** [comment]
There already is something similar called "Background Choice: Animated Album Art"

![example](https://github.com/daksh2k/Spicetify-stuff/assets/63104422/bcf59c15-f961-4586-ba94-4534f4a33ba0)

Is this what you're looking for?

**Comment by daksh2k** [comment]
Closing this, the feature is already there.

**Comment by adambnmohd** [comment]
Sorry for that, I had an old version
