### ISSUE TITLE
[Feature Request]: Like Button Background

### ISSUE THREAD

**Issue by beastlybrayden** [daksh2k/Spicetify-stuff#95]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Is it possible to add a small background to the like button in full screen mode? I use a AutoHotkey script to detect the like button but because the background is dynamic in the fullscreen view I can't detect the button. I assume it pulls an image for the like button so can that just be replaced with a non-transparent version of the like button? I'm happy to try and do it on my own, it wouldn't need to be a whole feature. I just want to know if it can be done.

**Comment by daksh2k** [comment]
Hi, I didn't get what you meant by a like button background. It's just a colour on an icon button, you can remove it entirely using CSS, or if you don't want it to be dynamic, you can turn off the setting called themed buttons from the settings menu.
