### ISSUE TITLE
[Feature Request]: 15-second-skip button controls

### ISSUE THREAD

**Issue by nick21500** [daksh2k/Spicetify-stuff#96]
### Choose the extension for feature request.

Full Screen Mode

### 📝 Provide a description of the new feature

Spotify shows little 15-second skip buttons when you're listening to a podcast.
If possible, it would be cool to see it in similar situations or just when "Extra Controls" is enabled on FSM :3

**Comment by daksh2k** [comment]
Hi @nick21500, I thought about adding support for podcasts overall on the extension, but then dropped it, as Spotify already has pretty good support and UI for podcasts, and the full-screen extension is catered more towards songs.

And now with video podcasts becoming more common, it makes more sense to use that only, with pip, cinema mode features.

<img width="1792" alt="image" src="https://github.com/daksh2k/Spicetify-stuff/assets/42179185/bc7c33ca-7fd2-4fa6-ae6f-0f1faf81c704">
