### ISSUE TITLE
[Bug]: Wrong application title

### ISSUE THREAD

**Issue by thangisme** [daksh2k/Spicetify-stuff#97]
### 🔍 Have you checked that you are using an auto updating method or latest version of the extension?

- [X] I have checked that I am on the latest version.

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### Choose the extension for bug report.

Full Screen Mode

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.13.661.ga588f749
- Spicetify version: v2.20.3
```

### 📝 Description

Initially when open full screen, the spotify windows title will be replaced with the song title, but when the song change, the title remain the same. It should change according to the new song

### 📸 Screenshots

![image](https://github.com/daksh2k/Spicetify-stuff/assets/35835961/e92fab2e-802a-434e-a455-74a7b25ea59f)

**Comment by daksh2k** [comment]
Actually, that is controlled by the spotify client itself, the extension plays no role in handling that.
